-- Migration 004: Vector Support
-- Enables pgvector extension and creates the post_embeddings table.
-- Embeddings are generated by the Infinity service (python/embeddings_service.py).
-- HNSW index chosen over IVFFlat: 15.5x faster at query time (40.5 vs 2.6 QPS
-- at 0.998 recall). Higher build cost (~4065s vs ~128s) is a one-time cost.

CREATE EXTENSION IF NOT EXISTS vector;

-- Post embeddings: one row per raw_post, generated by all-MiniLM-L6-v2 (384-dim)
-- UNIQUE constraint: one embedding per post — overwrite not allowed, only delete+insert
CREATE TABLE post_embeddings (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    raw_post_id     UUID NOT NULL REFERENCES raw_posts(id) UNIQUE,
    embedding       VECTOR(384),                    -- all-MiniLM-L6-v2 output (384 dimensions)
    model_name      TEXT NOT NULL DEFAULT 'sentence-transformers/all-MiniLM-L6-v2',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- HNSW approximate nearest-neighbor index for cosine similarity search
-- m=16: edges per node — good balance of memory and recall
-- ef_construction=400: higher = better quality index at build time
CREATE INDEX idx_embeddings_hnsw ON post_embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 400);
