-- Migration 014: methodology alignment (ADR 0001).
--
-- `npm run replay` reported config drift between the registered methodology
-- and the code: relevance@1.0.0 lists 18 keywords and a 0.1-per-match rule
-- (the code scores a 20-keyword lexicon as the matched fraction), and
-- discourse@1.0.0-DQI lists six weighted dimensions the code does not
-- compute. Existing rows are NEVER edited. This migration registers NEW rows
-- that state exactly what src/pipeline does — relevance@1.1.0 (including the
-- reachable one-match embedding gate), discourse@1.1.0-DQI and ingest@1.1.0
-- (collector payload allowlist, location basis).
--
-- The released sentiment / relevance / discourse 1.0.0 rows were previously
-- inserted only by scripts/seed.js. They are registered here FIRST (ON
-- CONFLICT DO NOTHING, so existing databases are unchanged) so that on a
-- fresh database every 1.0.0 row predates its 1.1.0 successor: a later
-- `npm run seed` can then never insert an older version with a newer
-- effective_from. The pipeline itself records the version the code
-- implements (CURRENT_VERSIONS), not the newest timestamp.
--
-- Generated by: node scripts/generate-methodology-migration.js <component@version ...>
-- Mirrors src/config/methodology-registry.js FIELD FOR FIELD
-- (tests/unit/pure/methodologyRegistry.test.js parses this file).

-- sentiment@1.0.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'sentiment',
    '1.0.0',
    'afinn-sentiment-npm-v5.0.2',
    $cfg${
    "positive_threshold": 0.05,
    "negative_threshold": -0.05,
    "accuracy_target": 0.99,
    "accuracy_note": "Phase 1 baseline — validates audit pattern. RoBERTa v2.0.0 targets 99% on benchmark."
}$cfg$::jsonb,
    $just$AFINN-165 English word list (Nielsen 2011). Comparative score = raw_score / token_count (normalizes for post length). Thresholds ±0.05 separate meaningful sentiment from noise, derived from distribution analysis of AI discourse corpus (pulse-of-ai-evidence-based-thresholds.pdf §3). Phase 1 establishes the audit trail pattern; Phase 2 upgrades to RoBERTa for the 99% accuracy target.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- relevance@1.0.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'relevance',
    '1.0.0',
    'keyword-relevance-v1.0',
    $cfg${
    "keywords": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural network",
        "chatgpt",
        "gpt",
        "llm",
        "ai",
        "automation",
        "algorithm",
        "robot",
        "autonomous",
        "computer vision",
        "natural language processing",
        "generative ai",
        "openai",
        "anthropic",
        "foundation model"
    ],
    "score_per_match": 0.1,
    "max_score": 1,
    "ai_relevance_threshold": 0.99
}$cfg$::jsonb,
    $just$Domain keyword taxonomy from AI academic literature and conference proceedings. Each matched keyword contributes 0.1 to relevance score, capped at 1.0. Threshold 0.99 ensures near-perfect AI-relevance filtering. Phase 2 upgrades to embedding-based hybrid scoring for improved recall on implicit AI discourse.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- discourse@1.0.0-DQI
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'discourse',
    '1.0.0-DQI',
    'deliberative-quality-index-v1.0',
    $cfg${
    "dimensions": {
        "participation": {
            "weight": 0.15
        },
        "justification_level": {
            "weight": 0.3
        },
        "justification_content": {
            "weight": 0.15
        },
        "counterargument_respect": {
            "weight": 0.2
        },
        "constructiveness": {
            "weight": 0.1
        },
        "respect_for_groups": {
            "weight": 0.1
        }
    },
    "source_category_weights": {
        "academic": 1.5,
        "policy": 1.3,
        "news": 1.2,
        "developer": 1.1,
        "nonprofit": 1,
        "blog": 0.9,
        "social": 0.8
    },
    "accuracy_target": 0.99,
    "novelty_cosine_threshold": 0.4,
    "echo_chamber_cosine_threshold": 0.15
}$cfg$::jsonb,
    $just$Deliberative Quality Index (DQI) — Steenbergen et al. (2003), operationalizing Habermas deliberative democracy theory. Applied to AI discourse with four improvements: (1) semantic argument deduplication via embeddings (cosine > 0.4 = novel), (2) echo chamber detection via cross-platform spread, (3) source authority weighting by category credibility, (4) NLP claim-evidence linkage detection. See TECHNICAL_SPEC.md §18.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- relevance@1.1.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'relevance',
    '1.1.0',
    'keyword-relevance-v1',
    $cfg${
    "keywords": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural network",
        "large language model",
        "llm",
        "natural language processing",
        "nlp",
        "transformer",
        "reinforcement learning",
        "generative ai",
        "computer vision",
        "foundation model",
        "fine-tuning",
        "embeddings",
        "gpt",
        "bert",
        "diffusion model",
        "autonomous agent",
        "ai safety"
    ],
    "matching": "case-insensitive substring match; each keyword counted once",
    "score_rule": "unique matched keywords / number of keywords, capped at 1.0",
    "score_per_match": 0.05,
    "max_score": 1,
    "is_relevant_rule": "score > 0 (at least one keyword matched)",
    "embed_gate_min_score": 0.05,
    "embed_gate_rule": "a post is embedded when its relevance score is at least 1/20 (one lexicon match); replaces the unreachable 0.40 gate, which needed 8 of the 20 keywords"
}$cfg$::jsonb,
    $just$Registers the relevance scorer exactly as the code runs it, after the replay tool found the 1.0.0 row out of step with the code (18 registered keywords and a 0.1-per-match rule, against a 20-keyword lexicon scored as the matched fraction). Score = unique lexicon keywords found in the post (case-insensitive substring) divided by 20, capped at 1.0; a post is AI-relevant when at least one keyword matches. The embedding gate moves from 0.40, which required 8 of 20 keywords and was never reached, to one keyword match (score >= 0.05), so relevant posts are embedded for semantic search. Collection is already scoped to each source's AI or technology feed; this score measures how explicitly a post uses AI vocabulary.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- discourse@1.1.0-DQI
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'discourse',
    '1.1.0-DQI',
    'dqi-heuristic-v1',
    $cfg${
    "dimensions": {
        "participation": {
            "weight": 0.2,
            "rule": "1.0 at 50+ words, 0.5 at 15-49 words, else 0"
        },
        "justification": {
            "weight": 0.2,
            "rule": "1.0 for 2+ reasoning connectors, 0.5 for 1, else 0"
        },
        "respectfulness": {
            "weight": 0.2,
            "rule": "1.0 minus 0.25 per hostile marker, floor 0"
        },
        "constructiveness": {
            "weight": 0.2,
            "rule": "1.0 for 3+ solution markers, 0.5 for 1-2, else 0"
        },
        "evidence": {
            "weight": 0.2,
            "rule": "1.0 for 2+ evidence markers, 0.5 for 1, else 0"
        }
    },
    "total_rule": "unweighted mean of the five dimension scores, in [0, 1]",
    "source_category_weighting": "none in this version"
}$cfg$::jsonb,
    $just$Registers the Deliberative Quality Index scorer exactly as the code runs it (Steenbergen et al. 2003, adapted as keyword heuristics), after the replay tool found the 1.0.0-DQI row describing six weighted dimensions and source-category weights the code does not apply. The code scores five dimensions (participation, justification, respectfulness, constructiveness, evidence), each 0, 0.5 or 1 from marker counts (respectfulness deducts 0.25 per hostile marker), and the total is their unweighted mean. No source-category weighting, semantic deduplication or echo-chamber signal is applied in this version.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- ingest@1.1.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'ingest',
    '1.1.0',
    'pulse-ingest-v1',
    $cfg${
    "pii_fields_removed": [
        "author",
        "author_fullname",
        "author_id",
        "authors",
        "username",
        "user",
        "user_id",
        "screen_name",
        "creator",
        "uploader",
        "owner",
        "email"
    ],
    "collector_payload": "collectors build the stored payload from an allowlist of content fields; identity fields are never requested",
    "location_granularity": "city",
    "location_basis": [
        "content",
        "publisher"
    ],
    "dedup_strategy": "unique (source, external id); sha256-content-hash join key",
    "legal_basis": "GDPR Article 6(1)(f) - Legitimate Interest"
}$cfg$::jsonb,
    $just$Real collection (ADR 0001): each collector builds the stored payload from an allowlist of content fields (title, text, link, timestamp, licence) and never requests author, username or profile-location fields; the ingest step still removes any identity field that arrives. Location is kept at city level only and comes from a content-level field (for example a geotag rounded to the nearest registry city) or, for editorial sources publishing their own articles, the publisher's home city, with the basis recorded on the post; a person's location is never inferred. Content is SHA-256 hashed as the immutable join key; duplicates are dropped per source and external id. Processing rests on legitimate interest (GDPR Art. 6(1)(f)) - aggregate discourse measurement over public posts with no profiling of identifiable individuals.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
