-- Migration 014: ingest@1.2.0 — in-text identity redaction (ADR 0001).
--
-- Collectors now replace e-mail addresses with [email] and @handles with
-- @[user] in the text before a post is stored (src/collectors/normalize.js
-- redactIdentities), found via a live GitHub issue title that carried a
-- handle. Released rows are never edited: ingest@1.1.0 (migration 013)
-- keeps its row; this is a NEW version.
--
-- Generated by: node scripts/generate-methodology-migration.js ingest@1.2.0
-- Mirrors src/config/methodology-registry.js FIELD FOR FIELD
-- (tests/unit/pure/methodologyRegistry.test.js parses this file).

-- ingest@1.2.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'ingest',
    '1.2.0',
    'pulse-ingest-v1',
    $cfg${
    "pii_fields_removed": [
        "author",
        "author_fullname",
        "author_id",
        "authors",
        "username",
        "user",
        "user_id",
        "screen_name",
        "creator",
        "uploader",
        "owner",
        "email"
    ],
    "collector_payload": "collectors build the stored payload from an allowlist of content fields; identity fields are never requested",
    "text_redaction": {
        "email_addresses": "[email]",
        "at_handles": "@[user]"
    },
    "identity_links": "links whose path names a person (/user/, /u/, /@name) are not stored",
    "location_granularity": "city",
    "location_basis": [
        "content",
        "publisher"
    ],
    "dedup_strategy": "unique (source, external id); sha256-content-hash join key",
    "legal_basis": "GDPR Article 6(1)(f) - Legitimate Interest"
}$cfg$::jsonb,
    $just$Adds in-text identity redaction to real collection (ADR 0001): besides building the stored payload from an allowlist of content fields and removing any identity field that arrives, e-mail addresses in the text become [email] and @handles (mentions, pings) become @[user] before the post is stored, and links whose path names a person are not kept. Location stays at city level from a content-level field or, for editorial sources, the publisher's home city, with the basis recorded; a person's location is never inferred. Content is SHA-256 hashed as the immutable join key; duplicates are dropped per source and external id. Processing rests on legitimate interest (GDPR Art. 6(1)(f)) - aggregate discourse measurement over public posts with no profiling of identifiable individuals.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
