-- Migration 017: ingest@1.3.0 and audit_narration@1.3.0 — decision D2 (2026-09-29): wider in-text
-- redaction, the precise privacy claim, and the provenance fingerprint.
--
-- raw_posts.provenance_fingerprint (additive, nullable): HMAC-SHA256(
-- PROVENANCE_KEY or AUDIT_HASH_KEY, source_slug || ':' || raw upstream id ||
-- ':' || canonical source URL), written at insert by collectors
-- (src/collectors/provenance.js). NULL for rows collected before 1.3.0, for
-- demo and seeded rows, and when no key is configured. `npm run
-- verify-provenance -- --post <id> --url <original>` reproduces it.
--
-- audit_narration@1.3.0: the receipt's live ingestion step restates the
-- ingest version's precise privacy claim and shows the provenance.
--
-- Released methodology rows are never edited: ingest@1.2.0 (migration 015)
-- and audit_narration@1.2.0 (migration 011) keep their rows; these are NEW
-- versions.
--
-- The INSERTs below are generated by:
--   node scripts/generate-methodology-migration.js ingest@1.3.0 audit_narration@1.3.0
-- and mirrors src/config/methodology-registry.js FIELD FOR FIELD
-- (tests/unit/pure/methodologyRegistry.test.js parses this file).

ALTER TABLE raw_posts ADD COLUMN IF NOT EXISTS provenance_fingerprint TEXT;
CREATE INDEX IF NOT EXISTS idx_raw_posts_provenance
    ON raw_posts(provenance_fingerprint) WHERE provenance_fingerprint IS NOT NULL;

-- ingest@1.3.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'ingest',
    '1.3.0',
    'pulse-ingest-v1',
    $cfg${
    "pii_fields_removed": [
        "author",
        "author_fullname",
        "author_id",
        "authors",
        "username",
        "user",
        "user_id",
        "screen_name",
        "creator",
        "uploader",
        "owner",
        "email"
    ],
    "collector_payload": "collectors build the stored payload from an allowlist of content fields; identity fields are never requested",
    "text_redaction": {
        "email_addresses": "[email]",
        "at_handles": "@[user]",
        "phone_numbers": "[phone] (E.164 and NANP)",
        "identity_links": "[profile link]",
        "cc_names": "cc [name]",
        "trailing_signoffs": "removed",
        "wikipedia_unsigned": "removed"
    },
    "identity_links": "links that point at a person (/user/, /u/, /profile/, /@name, github.com/<user>, gitlab.com/<user>, x.com and twitter.com handles, linkedin.com/in/, medium.com/<name>, a <name>.substack.com root, facebook, instagram, t.me, YouTube channels, Wikipedia User pages) are not stored and are replaced in text",
    "privacy_claim": "identity fields are never stored; e-mail addresses, handles, phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content",
    "external_ids": "the upstream id is stored only when it is not identity-bearing (numeric, arXiv, PMID, DOI, HN item ids, clean slugs); otherwise its keyed fingerprint is stored; the Telegram chat id is fingerprinted",
    "provenance": "HMAC-SHA256(PROVENANCE_KEY or AUDIT_HASH_KEY, source_slug + \":\" + raw upstream id + \":\" + canonical source URL), stored per post; reproduced by npm run verify-provenance -- --post <id> --url <original>",
    "location_granularity": "city",
    "location_basis": [
        "content",
        "publisher"
    ],
    "dedup_strategy": "unique (source, external id); sha256-content-hash join key",
    "legal_basis": "GDPR Article 6(1)(f) - Legitimate Interest"
}$cfg$::jsonb,
    $just$Decision D2 (2026-09-29): "both yet we need an identifier to be able to prove the audit traceability back to the source." Precise claim: identity fields are never stored; e-mail addresses, handles, phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content. Collectors build the stored payload from an allowlist of content fields and the ingest step removes any identity field that arrives. Before a post is stored, e-mail addresses become [email], @handles become @[user], phone numbers (E.164 and North American formats) become [phone], links to a person's profile become [profile link], "cc <Name>" becomes "cc [name]", and a trailing sign-off or a Wikipedia unsigned-comment note is removed. Each post carries a provenance fingerprint, a keyed HMAC of the source, the upstream id and the source URL, so anyone holding the original link can prove which item a post came from without the post storing anything that identifies a person; an upstream id that could identify someone is stored only as its fingerprint. Location stays at city level from a content-level field or, for editorial sources, the publisher's home city, with the basis recorded. Content is SHA-256 hashed as the immutable join key; duplicates are dropped per source and external id. Processing rests on legitimate interest (GDPR Art. 6(1)(f)) - aggregate discourse measurement over public posts with no profiling of identifiable individuals.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- audit_narration@1.3.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'audit_narration',
    '1.3.0',
    'pulse-narration-templates-v1',
    $cfg${
    "audiences": [
        "public",
        "plain",
        "config",
        "researcher"
    ],
    "renderer": "src/config/audit-narration.js",
    "rendering": "read-time deterministic templates over stored decision_audit_log output + methodology config; no per-post prose is generated or persisted",
    "reproduce_command": "npm run replay -- --post {post_id}",
    "verify_provenance_command": "npm run verify-provenance -- --post {post_id} --url <original URL> [--id <original id>]",
    "ingest_branches": [
        "live_source",
        "demo_feed"
    ],
    "demo_source_type": "demo",
    "provenance_fields": [
        "source",
        "published_at",
        "permalink",
        "external_id",
        "fingerprint",
        "verifiable"
    ]
}$cfg$::jsonb,
    $just$The audit endpoint serves four audience representations (public, journalist, regulator, researcher) of every decision step. The wording is part of the auditable surface, so the template set is registered here and version-bumped on any change — the API reports which narration version rendered a receipt. Templates only restate stored facts; they never invent per-post content. 1.3.0 implements decision D2 in the ingestion step for real sources: instead of saying that anything that could identify the writer was removed, it restates the privacy claim registered by the ingest version (identity fields are never stored; e-mail addresses, handles, phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content), and it shows the post's provenance - the source, its published time, the permalink when it does not identify a person, the stored external id and the provenance fingerprint - with the words "verifiable: provide the original URL or id to reproduce the fingerprint" and the command npm run verify-provenance that does so. Demo-feed wording and every inference step are unchanged from 1.2.0.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
