-- Migration 027: bias@1.2.0 — decision D3 (ADR 0001).
--
-- Jennifer, 2026-09-29, verbatim: "Separate layer, excluded from bias."
-- Posts placed at their publisher's home city (raw_payload.location_basis =
-- 'publisher': an editorial source's article with no content-level
-- location) are shown on the globe as a separate, labelled
-- publisher-location layer and are EXCLUDED from the location-concentration
-- check (src/pipeline/bias.js reads config.location_basis_excluded). Every
-- other threshold and name is bias@1.1.0's. Released rows are never edited:
-- bias@1.1.0 (migration 009) keeps its row, and bias_assessments rows keep
-- the version they ran under (methodology_version_id, migration 010).
--
-- The INSERT below is generated by:
--   node scripts/generate-methodology-migration.js bias@1.2.0
-- and mirrors src/config/methodology-registry.js FIELD FOR FIELD
-- (tests/unit/pure/methodologyRegistry.test.js parses this file).

-- bias@1.2.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'bias',
    '1.2.0',
    'pulse-bias-monitor-v1',
    $cfg${
    "location_concentration_max": 0.35,
    "platform_parity_max_diff": 0.3,
    "negative_dominance_max": 0.6,
    "layer_names": {
        "location_concentration": "Location concentration",
        "platform_sentiment_parity": "Demographic parity",
        "negative_dominance": "Negative dominance"
    },
    "layer_notes": {
        "platform_sentiment_parity": "parity measured across source categories (platform), not user demographics",
        "location_concentration": "content-located posts only: posts placed at the publisher's home city are shown as a separate publisher-location layer and excluded from this check (ADR 0001 D3)"
    },
    "citations": {
        "location_concentration": "Suresh & Guttag (2021)",
        "platform_sentiment_parity": "Barocas & Selbst (2016)",
        "negative_dominance": "Suresh & Guttag (2021)"
    },
    "planned_layers": [
        {
            "id": "equalized_odds",
            "name": "Equalized odds",
            "citation": "Hardt et al. (2016)",
            "note": "Phase 3 — not yet enforced"
        },
        {
            "id": "counterfactual_fairness",
            "name": "Counterfactual fairness",
            "citation": "Kusner et al. (2017)",
            "note": "Phase 3 — not yet enforced"
        }
    ],
    "layer_order": [
        "platform_sentiment_parity",
        "equalized_odds",
        "counterfactual_fairness"
    ],
    "legal_basis": "EU AI Act Article 13 - Transparency and provision of information",
    "location_basis_excluded": [
        "publisher"
    ],
    "location_concentration_scope": "posts located by their content (location_basis content, or no basis recorded); posts placed at the publisher's home city (location_basis publisher) are excluded and counted in the evidence"
}$cfg$::jsonb,
    $just$bias@1.2.0 applies decision D3 (ADR 0001, Jennifer 2026-09-29, verbatim: "Separate layer, excluded from bias."). A post from an editorial source with no content-level location is placed at the publisher's home city (BBC in London, NPR in Washington, D.C.) and recorded with location_basis publisher. That city says where the outlet is, not where the discussion happened, so it is not evidence of geographic concentration: the location-concentration check now counts only posts located by their content (or with no basis recorded) and states how many publisher-located posts it excluded. The globe shows publisher-located posts as a separate, labelled publisher-location layer. Platform sentiment parity and negative dominance are unchanged, and every threshold, name, citation and planned layer is as in bias@1.1.0: three fairness checks run after every processing job (platform sentiment parity across source categories, Barocas & Selbst 2016; location concentration, Suresh & Guttag 2021; negative dominance), with thresholds in this config so they are auditable and versioned (AI Act Article 13). Equalized odds and counterfactual fairness remain declared planned layers reported as not yet enforced.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
