-- Migration 028: bias@1.3.0 (PR #10 review P10-5) and an audited
-- resolution of the stale location-concentration alerts.
--
-- 1. alert_resolutions — one row per alert resolved by a documented
--    decision instead of by a check clearing it: who, when, why, and the
--    evidence (basis). Nothing is deleted; alert_events keeps every row and
--    gains resolved_at plus details.resolution pointing here.
--
-- 2. The stale alerts. Before the collection-cycle fix, one-source cron
--    jobs raised location-concentration alerts that measured the job's
--    shape (every located BBC post is in London), not the discourse. Every
--    OPEN location_concentration alert whose job bias@1.3.0 would not flag
--    is resolved: its job is re-evaluated from the stored rows
--    (decision_audit_log job_id → raw_posts) with bias@1.2.0/1.3.0's rules —
--    publisher-located posts excluded (decision D3, "Separate layer,
--    excluded from bias."), at least 30 content-located posts
--    (location_min_sample), dominant share above 0.35
--    (location_concentration_max). An alert whose job still fails those
--    rules stays open. Idempotent: an alert already resolved, or already in
--    alert_resolutions, is never touched again.
--
-- 3. bias@1.3.0 — the minimum sample: fewer than 30 content-located posts
--    records "insufficient sample" with no violation and no alert
--    (src/pipeline/bias.js). bias@1.1.0 / 1.2.0 are never edited. The
--    INSERT at the end is generated by:
--      node scripts/generate-methodology-migration.js bias@1.3.0
--    and mirrors src/config/methodology-registry.js FIELD FOR FIELD.

CREATE TABLE IF NOT EXISTS alert_resolutions (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    alert_id     UUID NOT NULL UNIQUE REFERENCES alert_events(id),
    resolved_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_by  TEXT NOT NULL,
    resolution   TEXT NOT NULL,
    basis        JSONB NOT NULL
);

WITH open_alerts AS (
    SELECT ae.id, (ae.details->>'jobId')::uuid AS job_id
    FROM alert_events ae
    WHERE ae.alert_type = 'location_concentration'
      AND ae.resolved_at IS NULL
      AND ae.details->>'jobId' ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      AND NOT EXISTS (SELECT 1 FROM alert_resolutions r WHERE r.alert_id = ae.id)
),
job_posts AS (
    SELECT DISTINCT oa.id AS alert_id, rp.id AS post_id, rp.location,
           COALESCE(rp.raw_payload->>'location_basis', 'content') AS basis
    FROM open_alerts oa
    JOIN decision_audit_log d ON d.job_id = oa.job_id AND d.decision_type = 'sentiment'
    JOIN raw_posts rp ON rp.id = d.raw_post_id
    WHERE rp.location IS NOT NULL AND rp.location <> ''
),
per_city AS (
    SELECT alert_id, location, COUNT(*)::int AS n
    FROM job_posts WHERE basis <> 'publisher'
    GROUP BY alert_id, location
),
evaluated AS (
    SELECT oa.id AS alert_id, oa.job_id,
           COALESCE((SELECT SUM(n) FROM per_city pc WHERE pc.alert_id = oa.id), 0)::int AS content_located,
           COALESCE((SELECT MAX(n) FROM per_city pc WHERE pc.alert_id = oa.id), 0)::int AS dominant,
           (SELECT COUNT(*) FROM job_posts jp WHERE jp.alert_id = oa.id AND jp.basis = 'publisher')::int AS publisher_located
    FROM open_alerts oa
),
stale AS (
    SELECT e.*,
           CASE WHEN e.content_located < 30 THEN 'insufficient sample'
                ELSE 'within threshold once publisher-located posts are excluded' END AS verdict
    FROM evaluated e
    WHERE e.content_located < 30 OR e.dominant::float8 / NULLIF(e.content_located, 0) <= 0.35
),
recorded AS (
    INSERT INTO alert_resolutions (alert_id, resolved_by, resolution, basis)
    SELECT s.alert_id,
           'migration 028_bias_min_sample.sql',
           'Resolved as stale: re-evaluated under bias@1.3.0 (' || s.verdict || '); the alert measured the shape of a '
               || 'one-source collection run, not the discourse (PR #10 review P10-5; ADR 0001 D3).',
           jsonb_build_object(
               'job_id', s.job_id,
               'methodology', 'bias@1.3.0',
               'content_located_posts', s.content_located,
               'publisher_located_posts_excluded', s.publisher_located,
               'dominant_city_posts', s.dominant,
               'dominant_share', CASE WHEN s.content_located > 0 THEN round((s.dominant::numeric / s.content_located), 4) END,
               'min_sample', 30,
               'threshold', 0.35,
               'verdict', s.verdict)
    FROM stale s
    ON CONFLICT (alert_id) DO NOTHING
    RETURNING id, alert_id
)
UPDATE alert_events ae
SET resolved_at = NOW(),
    details = COALESCE(ae.details, '{}'::jsonb)
        || jsonb_build_object('resolution', 'stale: see alert_resolutions ' || r.id::text || ' (migration 028, bias@1.3.0)')
FROM recorded r
WHERE ae.id = r.alert_id AND ae.resolved_at IS NULL;

-- bias@1.3.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'bias',
    '1.3.0',
    'pulse-bias-monitor-v1',
    $cfg${
    "location_concentration_max": 0.35,
    "platform_parity_max_diff": 0.3,
    "negative_dominance_max": 0.6,
    "layer_names": {
        "location_concentration": "Location concentration",
        "platform_sentiment_parity": "Demographic parity",
        "negative_dominance": "Negative dominance"
    },
    "layer_notes": {
        "platform_sentiment_parity": "parity measured across source categories (platform), not user demographics",
        "location_concentration": "content-located posts only (publisher-located posts are a separate layer, ADR 0001 D3); needs at least 30 of them, else \"insufficient sample\" and no alert"
    },
    "citations": {
        "location_concentration": "Suresh & Guttag (2021)",
        "platform_sentiment_parity": "Barocas & Selbst (2016)",
        "negative_dominance": "Suresh & Guttag (2021)"
    },
    "planned_layers": [
        {
            "id": "equalized_odds",
            "name": "Equalized odds",
            "citation": "Hardt et al. (2016)",
            "note": "Phase 3 — not yet enforced"
        },
        {
            "id": "counterfactual_fairness",
            "name": "Counterfactual fairness",
            "citation": "Kusner et al. (2017)",
            "note": "Phase 3 — not yet enforced"
        }
    ],
    "layer_order": [
        "platform_sentiment_parity",
        "equalized_odds",
        "counterfactual_fairness"
    ],
    "legal_basis": "EU AI Act Article 13 - Transparency and provision of information",
    "location_basis_excluded": [
        "publisher"
    ],
    "location_concentration_scope": "posts located by their content (location_basis content, or no basis recorded); posts placed at the publisher's home city (location_basis publisher) are excluded and counted in the evidence",
    "location_min_sample": 30,
    "location_min_sample_rule": "fewer than 30 content-located posts in the job: the assessment is recorded as \"insufficient sample\" with its share stated, no violation and no alert"
}$cfg$::jsonb,
    $just$bias@1.3.0 adds a minimum sample to the location-concentration check (PR #10 review P10-5). A share computed over a handful of located posts measures the shape of one collection run, not the discourse: a scheduled run of one editorial source had all its located posts in one city and read 1.000, raising critical alerts that said nothing about the posts. The check now needs at least 30 content-located posts in the job; below that it records an "insufficient sample" assessment with the share still stated, and raises no violation and no alert. As in bias@1.2.0 (decision D3, "Separate layer, excluded from bias."), posts placed at the publisher's home city are excluded from this check and counted in its evidence. Platform sentiment parity (Barocas & Selbst 2016) and negative dominance are unchanged, every threshold, layer name, citation and planned layer is as in bias@1.1.0 (AI Act Article 13), and equalized odds and counterfactual fairness remain declared planned layers reported as not yet enforced. Open location-concentration alerts that this version would not raise are resolved by migration 028 with an audited alert_resolutions record, never deleted.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
