-- Migration 029: relevance@1.2.0 (PR #10 review P10-13).
--
-- relevance@1.1.0 matched its 20 keywords as case-insensitive substrings, so
-- "Robert" matched "bert", and a post admitted by the collection filter for
-- "AI" alone scored 0. relevance@1.2.0 adds "AI" (21 terms) and matches every
-- term as whole words: case-sensitive "AI" (the same expression the
-- collection filter uses, src/config/ai-lexicon.js), case-sensitive "BERT",
-- whole-word acronyms, word boundaries for every phrase. Released rows are
-- never edited: 1.0.0 and 1.1.0 keep their rows, decisions keep the version
-- they were scored under, and `npm run replay` re-runs each with its own
-- version's rule (src/pipeline/relevance.js VERSIONS).
--
-- The INSERT below is generated by:
--   node scripts/generate-methodology-migration.js relevance@1.2.0
-- and mirrors src/config/methodology-registry.js FIELD FOR FIELD.

-- relevance@1.2.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'relevance',
    '1.2.0',
    'keyword-relevance-v2',
    $cfg${
    "keywords": [
        "artificial intelligence",
        "machine learning",
        "deep learning",
        "neural network",
        "large language model",
        "llm",
        "natural language processing",
        "nlp",
        "transformer",
        "reinforcement learning",
        "generative ai",
        "computer vision",
        "foundation model",
        "fine-tuning",
        "embeddings",
        "gpt",
        "bert",
        "diffusion model",
        "autonomous agent",
        "ai safety",
        "AI"
    ],
    "matching": {
        "artificial intelligence": "whole words, any case, space or hyphen between words, plural allowed",
        "machine learning": "whole words, any case, space or hyphen between words, plural allowed",
        "deep learning": "whole words, any case, space or hyphen between words, plural allowed",
        "neural network": "whole words, any case, space or hyphen between words, plural allowed",
        "large language model": "whole words, any case, space or hyphen between words, plural allowed",
        "llm": "whole word, any case, plural allowed",
        "natural language processing": "whole words, any case, space or hyphen between words, plural allowed",
        "nlp": "whole word, any case",
        "transformer": "whole words, any case, space or hyphen between words, plural allowed",
        "reinforcement learning": "whole words, any case, space or hyphen between words, plural allowed",
        "generative ai": "whole words, any case, space or hyphen between words, plural allowed",
        "computer vision": "whole words, any case, space or hyphen between words, plural allowed",
        "foundation model": "whole words, any case, space or hyphen between words, plural allowed",
        "fine-tuning": "whole words, any case, space or hyphen between words, plural allowed",
        "embeddings": "whole words, any case, space or hyphen between words, plural allowed",
        "gpt": "whole word, any case; \"ChatGPT\" and a version suffix (GPT-4o) allowed",
        "bert": "case-sensitive whole word \"BERT\"",
        "diffusion model": "whole words, any case, space or hyphen between words, plural allowed",
        "autonomous agent": "whole words, any case, space or hyphen between words, plural allowed",
        "ai safety": "whole words, any case, space or hyphen between words, plural allowed",
        "AI": "case-sensitive whole word \"AI\" or \"A.I.\""
    },
    "shared_with": "src/collectors/ai-filter.js uses the same case-sensitive \"AI\" expression (src/config/ai-lexicon.js AI_ACRONYM_RE); the filter's wider product and topic patterns scope collection only and are not relevance terms",
    "score_rule": "unique matched terms / number of terms (21), capped at 1.0",
    "score_per_match": 0.047619047619047616,
    "max_score": 1,
    "is_relevant_rule": "score > 0 (at least one term matched)",
    "embed_gate_min_score": 0.047619047619047616,
    "embed_gate_rule": "a post is embedded when its relevance score is at least 1/21 (one term matched)"
}$cfg$::jsonb,
    $just$relevance@1.2.0 fixes false matches found in review (PR #10, P10-13). Version 1.1.0 matched every lexicon keyword as a case-insensitive substring, so "Robert" matched "bert", and a post that the collection filter admitted only because it said "AI" scored 0, since the lexicon had no "AI" term. Version 1.2.0 keeps the 20 terms of 1.1.0 and adds "AI" (21 terms). Every term now matches as whole words: "AI" (or "A.I.") only in upper case, the same rule the collection filter uses (one shared expression, src/config/ai-lexicon.js); "BERT" only in upper case, since Bert is a name; LLM and NLP as whole words in any case; "gpt" as a whole word with ChatGPT and a version suffix such as GPT-4o allowed; every other term in any case with word boundaries, a space or hyphen between words and a plural s allowed. Score = unique matched terms divided by 21, capped at 1.0; a post is AI-relevant when at least one term matches, and it is embedded at the same point (score >= 1/21). Collection is already scoped to each source's AI or technology feed; this score measures how explicitly a post uses AI vocabulary. Decisions scored under 1.1.0 keep their version and are replayed with the 1.1.0 rule.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
