-- Migration 031: genuine text retention (PR #10 review P10-2) and
-- ingest@1.6.0.
--
-- 1. An index for the retention job (src/collectors/retention.js): posts of
--    a source whose text is still stored, by collection time.
-- 2. ingest@1.6.0: the post text is stored once (raw_posts.content), never
--    duplicated in raw_payload; every stored post writes a 'collected'
--    data_retention_log row; each source's text window (Reddit 48 h,
--    Guardian 24 h, YouTube and TikTok 30 days, else the §19 90 days).
--    raw_posts.content is NOT NULL, so removal replaces it with a notice and
--    sets text_removed_at / text_removed_reason (migration 025's mechanism,
--    generalised; Jennifer's ruling 9, "Blank text, keep audit rows",
--    applied to the Guardian, YouTube and TikTok by analogy).
--    Released rows are never edited: ingest@1.5.0 keeps its row. No
--    existing post is changed here — the retention job blanks them as their
--    windows end, and writes the data_retention_log rows that say so.
--
-- The INSERT below is generated by:
--   node scripts/generate-methodology-migration.js ingest@1.6.0
-- and mirrors src/config/methodology-registry.js FIELD FOR FIELD.

CREATE INDEX IF NOT EXISTS idx_raw_posts_text_live
    ON raw_posts (source_id, collected_at)
    WHERE text_removed_at IS NULL;

-- ingest@1.6.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'ingest',
    '1.6.0',
    'pulse-ingest-v1',
    $cfg${
    "pii_fields_removed": [
        "author",
        "author_fullname",
        "author_id",
        "authors",
        "username",
        "user",
        "user_id",
        "screen_name",
        "creator",
        "uploader",
        "owner",
        "email"
    ],
    "collector_payload": "collectors build the stored payload from an allowlist of content fields; identity fields are never requested",
    "text_redaction": {
        "email_addresses": "[email]",
        "at_handles": "@[user]",
        "at_handle_min_length": 1,
        "reddit_user_handles": "u/[user] (u/<name> and /u/<name>); a scheme-less reddit.com/u/ or /user/ link becomes [profile link]",
        "phone_numbers": "[phone] (E.164 and NANP)",
        "identity_links": "[profile link]",
        "cc_names": "cc [name]",
        "trailing_signoffs": "removed",
        "wikipedia_unsigned": "removed"
    },
    "identity_links": "links that point at a person (/user/, /u/, /profile/, /@name, github.com/<user>, gitlab.com/<user>, x.com and twitter.com handles, linkedin.com/in/, medium.com/<name>, a <name>.substack.com root, facebook, instagram, t.me, YouTube channels, Wikipedia User pages) are not stored and are replaced in text",
    "privacy_claim": "identity fields are never stored; e-mail addresses, handles (including Reddit u/ names), phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content",
    "external_ids": "the upstream id is stored only when it is not identity-bearing (numeric, arXiv, PMID, DOI, HN item ids, Reddit t3_ fullnames, clean slugs); otherwise its keyed fingerprint is stored; the Telegram chat id is fingerprinted",
    "provenance": "HMAC-SHA256(PROVENANCE_KEY or AUDIT_HASH_KEY, source_slug + \":\" + raw upstream id + \":\" + canonical source URL), stored per post; reproduced by npm run verify-provenance -- --post <id> --url <original>",
    "location_granularity": "city",
    "location_basis": [
        "content",
        "publisher"
    ],
    "dedup_strategy": "unique (source, external id); sha256-content-hash join key",
    "legal_basis": "GDPR Article 6(1)(f) - Legitimate Interest",
    "payload_text_keys_not_stored": [
        "text",
        "title",
        "body",
        "content",
        "selftext"
    ],
    "text_storage": "the post text is stored once, in raw_posts.content; raw_payload keeps metadata only (url, published_at, location_basis, route, licence, attribution)",
    "collected_log": "every stored post writes a data_retention_log row, action collected, legal basis GDPR Article 6(1)(f), in the same statement as the insert",
    "text_retention": {
        "rule": "after its source's window the text is replaced by a removal notice (raw_posts.text_removed_at); scores and audit rows are kept (ADR 0001 ruling 9, \"Blank text, keep audit rows\")",
        "platform_terms_hours": {
            "reddit": 48,
            "guardian": 24,
            "youtube": 720,
            "tiktok": 720
        },
        "default": "RETENTION_DETAIL_DAYS (90) days, TECHNICAL_SPEC §19",
        "applied_by_analogy": [
            "guardian",
            "youtube",
            "tiktok"
        ]
    }
}$cfg$::jsonb,
    $just$ingest@1.6.0 makes retention genuine (PR #10 review P10-2). Until 1.5.0 the text and title were copied into raw_payload next to raw_posts.content, so removing the content left the text in the payload. From 1.6.0 the text is stored once, in raw_posts.content, and the payload keeps metadata only; every stored post also writes a collected row to data_retention_log (legal basis GDPR Article 6(1)(f)) in the same statement as the insert (TECHNICAL_SPEC §8). Each source has a text window: Reddit 48 hours (ADR 0001 ruling 9), the Guardian 24 hours (its terms), YouTube and TikTok 30 days (their API terms), every other source the §19 detail window of 90 days. When the window ends the text, and any legacy copy in the payload, is replaced by a removal notice and the url is dropped (Reddit keeps its slug-less permalink); the scores, audit rows, content hash and provenance fingerprint are kept, applying Jennifer's ruling 9 ("Blank text, keep audit rows") to the Guardian, YouTube and TikTok by analogy. Everything else is as in ingest@1.5.0: identity fields are never stored; e-mail addresses, handles (including Reddit u/ names), phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content; each post carries a keyed provenance fingerprint; location stays at city level with its basis recorded; processing rests on legitimate interest (GDPR Art. 6(1)(f)).$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
