-- Migration 032: bias@1.4.0 — a minimum sample for EVERY fairness check —
-- and an audited resolution of every open bias alert it would not raise.
--
-- Jennifer's live dashboard (2026-09-29) showed 39 active alerts, 31
-- critical: location concentration 1.000 for single publisher cities, and
-- demographic-parity watches between categories of a few posts, from
-- collection cycles of a handful of posts. bias@1.4.0 (src/pipeline/bias.js):
--   location concentration  >= 30 content-located posts, publisher-located
--                           posts excluded (bias@1.2.0/1.3.0, decision D3)
--   platform sentiment parity  only categories with >= 10 posts compared;
--                           fewer than two such categories: insufficient
--   negative dominance      >= 30 posts
-- Below a minimum: "insufficient sample", no violation, no alert.
--
-- 1. alert_resolutions.methodology_version_id (created by 028; added here
--    only for a database that ran an earlier draft of 028). No existing
--    resolution row is ever updated (PR #22 principal #9).
-- 2. bias@1.4.0 is registered (generated by
--      node scripts/generate-methodology-migration.js bias@1.4.0
--    and mirroring src/config/methodology-registry.js field for field).
-- 3. Every OPEN location_concentration, platform_sentiment_parity and
--    negative_dominance alert is re-evaluated from the stored rows of its
--    job under bias@1.4.0's rules; those it would not raise get an
--    alert_resolutions row (who, why, the evidence, the version) and
--    resolved_at plus details.resolution_ref (only when absent) on the
--    alert. The original alert
--    and bias_assessments rows are never deleted or rewritten otherwise; an
--    alert whose job still fails the rules stays open. Idempotent.

ALTER TABLE alert_resolutions ADD COLUMN IF NOT EXISTS methodology_version_id UUID REFERENCES methodology_versions(id);

-- bias@1.4.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'bias',
    '1.4.0',
    'pulse-bias-monitor-v1',
    $cfg${
    "location_concentration_max": 0.35,
    "platform_parity_max_diff": 0.3,
    "negative_dominance_max": 0.6,
    "layer_names": {
        "location_concentration": "Location concentration",
        "platform_sentiment_parity": "Demographic parity",
        "negative_dominance": "Negative dominance"
    },
    "layer_notes": {
        "platform_sentiment_parity": "parity measured across source categories (platform), not user demographics; only categories with at least 10 posts in the job are compared",
        "location_concentration": "content-located posts only (publisher-located posts are a separate layer, ADR 0001 D3); needs at least 30 of them, else \"insufficient sample\" and no alert",
        "negative_dominance": "needs at least 30 posts in the job, else \"insufficient sample\" and no alert"
    },
    "citations": {
        "location_concentration": "Suresh & Guttag (2021)",
        "platform_sentiment_parity": "Barocas & Selbst (2016)",
        "negative_dominance": "Suresh & Guttag (2021)"
    },
    "planned_layers": [
        {
            "id": "equalized_odds",
            "name": "Equalized odds",
            "citation": "Hardt et al. (2016)",
            "note": "Phase 3 — not yet enforced"
        },
        {
            "id": "counterfactual_fairness",
            "name": "Counterfactual fairness",
            "citation": "Kusner et al. (2017)",
            "note": "Phase 3 — not yet enforced"
        }
    ],
    "layer_order": [
        "platform_sentiment_parity",
        "equalized_odds",
        "counterfactual_fairness"
    ],
    "legal_basis": "EU AI Act Article 13 - Transparency and provision of information",
    "location_basis_excluded": [
        "publisher"
    ],
    "location_concentration_scope": "posts located by their content (location_basis content, or no basis recorded); posts placed at the publisher's home city (location_basis publisher) are excluded and counted in the evidence",
    "location_min_sample": 30,
    "location_min_sample_rule": "fewer than 30 content-located posts in the job: the assessment is recorded as \"insufficient sample\" with its share stated, no violation and no alert",
    "parity_min_per_category": 10,
    "negative_min_sample": 30,
    "sample_rules": {
        "location_concentration": "at least 30 content-located posts in the job (location_min_sample), publisher-located posts excluded",
        "platform_sentiment_parity": "only categories with at least 10 posts are compared (parity_min_per_category); fewer than two such categories: insufficient sample",
        "negative_dominance": "at least 30 posts in the job (negative_min_sample)",
        "below_minimum": "\"insufficient sample\": the value is stated, no violation, no alert",
        "basis": "n >= 30 is the conventional minimum for treating a sample proportion as approximately normal (central limit theorem rule of thumb); n >= 10 per group is the conventional floor for comparing group means. Both are deliberately conservative floors, not significance tests."
    }
}$cfg$::jsonb,
    $just$bias@1.4.0 gives every fairness check a minimum sample, after the live dashboard showed 39 active alerts from collection cycles of a few posts: location concentration of 1.000 for single publisher cities and demographic-parity watches between two categories of three or four posts each. Location concentration keeps bias@1.3.0's rule (at least 30 content-located posts; publisher-located posts excluded, decision D3 "Separate layer, excluded from bias."). Platform sentiment parity (the demographic-parity outcome gap across source categories, Barocas & Selbst 2016) now compares only categories with at least 10 posts in the job; with fewer than two such categories it records "insufficient sample". Negative dominance needs at least 30 posts. Below a minimum the assessment is recorded with its value, as "insufficient sample", with no violation and no alert. The floors are conventional (n >= 30 for a proportion to be treated as approximately normal; n >= 10 per group for comparing means) and are floors, not significance tests. Thresholds, names, citations (Suresh & Guttag 2021 for location and negative dominance) and planned layers are as in bias@1.1.0 (AI Act Article 13). Open alerts that this version would not raise are resolved by migration 032 with an audited alert_resolutions record linked to this version, never deleted.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

WITH open_alerts AS (
    SELECT ae.id, ae.alert_type, (ae.details->>'jobId')::uuid AS job_id
    FROM alert_events ae
    WHERE ae.alert_type IN ('location_concentration', 'platform_sentiment_parity', 'negative_dominance')
      AND ae.resolved_at IS NULL
      AND ae.details->>'jobId' ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      AND NOT EXISTS (SELECT 1 FROM alert_resolutions r WHERE r.alert_id = ae.id)
),
job_posts AS (
    SELECT DISTINCT oa.id AS alert_id, rp.id AS post_id, rp.location, ds.category,
           COALESCE(rp.raw_payload->>'location_basis', 'content') AS basis,
           sr.comparative, sr.indicator
    FROM open_alerts oa
    JOIN decision_audit_log d ON d.job_id = oa.job_id AND d.decision_type = 'sentiment'
    JOIN raw_posts rp ON rp.id = d.raw_post_id
    JOIN data_sources ds ON ds.id = rp.source_id
    LEFT JOIN sentiment_results sr ON sr.raw_post_id = rp.id
),
loc_city AS (
    SELECT alert_id, location, COUNT(*)::int AS n FROM job_posts
    WHERE location IS NOT NULL AND location <> '' AND basis <> 'publisher'
    GROUP BY alert_id, location
),
loc AS (
    SELECT oa.id AS alert_id,
           COALESCE((SELECT SUM(n) FROM loc_city c WHERE c.alert_id = oa.id), 0)::int AS sample,
           COALESCE((SELECT MAX(n) FROM loc_city c WHERE c.alert_id = oa.id), 0)::int AS dominant,
           (SELECT COUNT(*) FROM job_posts jp WHERE jp.alert_id = oa.id AND jp.location <> '' AND jp.basis = 'publisher')::int AS excluded
    FROM open_alerts oa WHERE oa.alert_type = 'location_concentration'
),
par_cat AS (
    SELECT alert_id, category, COUNT(*)::int AS n, AVG(comparative) AS avg_c
    FROM job_posts WHERE comparative IS NOT NULL GROUP BY alert_id, category
),
par AS (
    SELECT oa.id AS alert_id,
           (SELECT COUNT(*) FROM par_cat p WHERE p.alert_id = oa.id AND p.n >= 10)::int AS qualifying,
           (SELECT MAX(avg_c) - MIN(avg_c) FROM par_cat p WHERE p.alert_id = oa.id AND p.n >= 10) AS max_diff
    FROM open_alerts oa WHERE oa.alert_type = 'platform_sentiment_parity'
),
neg AS (
    SELECT oa.id AS alert_id,
           (SELECT COUNT(*) FROM job_posts jp WHERE jp.alert_id = oa.id AND jp.indicator IS NOT NULL)::int AS sample,
           (SELECT COUNT(*) FROM job_posts jp WHERE jp.alert_id = oa.id AND jp.indicator = 'negative')::int AS negatives
    FROM open_alerts oa WHERE oa.alert_type = 'negative_dominance'
),
stale AS (
    SELECT oa.id AS alert_id, oa.job_id, oa.alert_type,
           CASE WHEN l.sample < 30 THEN 'insufficient sample'
                ELSE 'within threshold once publisher-located posts are excluded' END AS verdict,
           jsonb_build_object('content_located_posts', l.sample, 'publisher_located_posts_excluded', l.excluded,
                              'dominant_city_posts', l.dominant, 'min_sample', 30, 'threshold', 0.35) AS evidence
    FROM open_alerts oa JOIN loc l ON l.alert_id = oa.id
    WHERE l.sample < 30 OR l.dominant::float8 / NULLIF(l.sample, 0) <= 0.35
    UNION ALL
    SELECT oa.id, oa.job_id, oa.alert_type,
           CASE WHEN p.qualifying < 2 THEN 'insufficient sample' ELSE 'within threshold' END,
           jsonb_build_object('categories_with_min_posts', p.qualifying, 'min_per_category', 10,
                              'max_comparative_diff', p.max_diff, 'threshold', 0.30)
    FROM open_alerts oa JOIN par p ON p.alert_id = oa.id
    WHERE p.qualifying < 2 OR p.max_diff <= 0.30
    UNION ALL
    SELECT oa.id, oa.job_id, oa.alert_type,
           CASE WHEN n.sample < 30 THEN 'insufficient sample' ELSE 'within threshold' END,
           jsonb_build_object('posts', n.sample, 'negative_posts', n.negatives, 'min_sample', 30, 'threshold', 0.60)
    FROM open_alerts oa JOIN neg n ON n.alert_id = oa.id
    WHERE n.sample < 30 OR n.negatives::float8 / NULLIF(n.sample, 0) <= 0.60
),
recorded AS (
    INSERT INTO alert_resolutions (alert_id, resolved_by, resolution, basis, methodology_version_id)
    SELECT s.alert_id,
           'migration 032_bias_sample_rules.sql',
           'Superseded by bias@1.4.0: ' || s.verdict || ' (' || s.alert_type || '); the alert measured the size of one '
               || 'collection cycle, not the discourse.',
           s.evidence || jsonb_build_object('job_id', s.job_id, 'methodology', 'bias@1.4.0', 'verdict', s.verdict),
           (SELECT id FROM methodology_versions WHERE component = 'bias' AND version = '1.4.0')
    FROM stale s
    ON CONFLICT (alert_id) DO NOTHING
    RETURNING id, alert_id
)
UPDATE alert_events ae
SET resolved_at = NOW(),
    details = CASE WHEN COALESCE(ae.details, '{}'::jsonb) ? 'resolution_ref' THEN ae.details
                   ELSE COALESCE(ae.details, '{}'::jsonb)
                        || jsonb_build_object('resolution_ref', 'alert_resolutions ' || r.id::text || ' (migration 032, bias@1.4.0)') END
FROM recorded r
WHERE ae.id = r.alert_id AND ae.resolved_at IS NULL;
