-- Migration 042: the collection admission filter is versioned methodology
-- (PR #22 review, decision G6, Jennifer McKinney 2026-09-29).
--
-- src/collectors/ai-filter.js decides which items of a site-wide or
-- technology feed are stored at all — a selection decision. It becomes the
-- methodology component admission_filter; version 1.0.0 registers exactly the
-- patterns in the code (tests/unit/pure/admissionFilter.test.js enforces it).
-- Every collected post records the admission version it was stored under
-- (raw_posts.admission_mv_id, set by the collection runner). Posts stored
-- before this migration keep NULL: they were admitted by the same code, but
-- no version was recorded then, and a released row is never back-filled by
-- guess. Demo posts are never admitted by the filter and stay NULL.
-- A change to the filter is a NEW version. Additive and idempotent.

ALTER TABLE raw_posts ADD COLUMN IF NOT EXISTS admission_mv_id UUID REFERENCES methodology_versions(id);

-- The INSERT below is generated by:
--   node scripts/generate-methodology-migration.js admission_filter@1.0.0
-- and mirrors src/config/methodology-registry.js FIELD FOR FIELD.

-- admission_filter@1.0.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'admission_filter',
    '1.0.0',
    'ai-scope-filter-v1',
    $cfg${
    "patterns": [
        {
            "source": "\\b(?:A\\.I\\.?|AI)(?![A-Za-z0-9])",
            "flags": ""
        },
        {
            "source": "\\bAGI\\b",
            "flags": ""
        },
        {
            "source": "\\bLLMs?\\b",
            "flags": ""
        },
        {
            "source": "\\bNLP\\b",
            "flags": ""
        },
        {
            "source": "\\bGPT(?:-?\\d(?:\\.\\d)?o?)?\\b",
            "flags": ""
        },
        {
            "source": "artificial[\\s-]intelligence",
            "flags": "i"
        },
        {
            "source": "machine[\\s-]learning",
            "flags": "i"
        },
        {
            "source": "deep[\\s-]learning",
            "flags": "i"
        },
        {
            "source": "neural[\\s-]net(?:work)?s?",
            "flags": "i"
        },
        {
            "source": "large[\\s-]language[\\s-]models?",
            "flags": "i"
        },
        {
            "source": "language[\\s-]models?",
            "flags": "i"
        },
        {
            "source": "generative\\s+(?:ai|models?|tools?)",
            "flags": "i"
        },
        {
            "source": "natural[\\s-]language[\\s-]processing",
            "flags": "i"
        },
        {
            "source": "computer[\\s-]vision",
            "flags": "i"
        },
        {
            "source": "\\b(?:chatbots?|chatgpt|openai|anthropic|deepmind|copilot|midjourney|hugging\\s?face|stable\\s+diffusion|mistral\\s+ai)\\b",
            "flags": "i"
        },
        {
            "source": "\\bdeepfakes?\\b",
            "flags": "i"
        },
        {
            "source": "facial[\\s-]recognition",
            "flags": "i"
        },
        {
            "source": "\\balgorithmic\\b",
            "flags": "i"
        },
        {
            "source": "\\bautonomous\\s+(?:vehicles?|agents?|weapons?|driving)\\b",
            "flags": "i"
        },
        {
            "source": "\\brobot(?:s|ics|axis?)?\\b",
            "flags": "i"
        }
    ],
    "match_rule": "an item is admitted when ANY pattern matches its title + summary text",
    "scope_rule": {
        "filter": "site-wide and technology feeds (registry route scope \"filter\"): only items the patterns match are stored",
        "ai": "AI-specific feeds and searches (route scope \"ai\"): every item is stored; the patterns are not applied"
    },
    "search_terms": [
        "\"artificial intelligence\"",
        "AI",
        "AGI",
        "LLM",
        "GPT",
        "ChatGPT",
        "OpenAI",
        "Anthropic",
        "DeepMind",
        "\"machine learning\"",
        "\"deep learning\"",
        "\"neural network\"",
        "\"language model\"",
        "\"generative AI\"",
        "NLP",
        "\"natural language processing\"",
        "\"computer vision\"",
        "chatbot",
        "Copilot",
        "Midjourney",
        "\"Hugging Face\"",
        "\"Stable Diffusion\"",
        "\"Mistral AI\"",
        "deepfake",
        "\"facial recognition\"",
        "algorithmic",
        "\"autonomous vehicles\"",
        "robotics"
    ],
    "search_terms_rule": "server-side search terms (Reddit subreddit discovery); every result is still filtered with the patterns",
    "shared_with": "the \"AI\" pattern is src/config/ai-lexicon.js AI_ACRONYM_RE, the same expression relevance@1.2.0 scores",
    "not_relevance": "admission scopes collection only; the relevance score (relevance@1.2.0) is a separate component"
}$cfg$::jsonb,
    $just$admission_filter@1.0.0 registers the collection admission filter as methodology (PR #22 review, decision G6, Jennifer McKinney 2026-09-29). The filter decides which items of a site-wide or technology feed are stored at all, which is a selection decision: it shapes every downstream measure. It was code-only until now; this version records exactly the patterns that ran since relevance@1.2.0 (PR #10 P10-13): upper-case "AI" or "A.I." as a whole word, AGI, LLM, NLP, GPT with a version suffix, and topic and product phrases (artificial intelligence, machine learning, deep learning, neural networks, language models, generative AI, natural language processing, computer vision, named AI products and labs, deepfakes, facial recognition, algorithmic, autonomous vehicles, agents or weapons, robots and robotics). An item is stored when any pattern matches its title and summary. AI-specific feeds are stored whole. Each collected post records the admission version it was stored under; a change to the patterns, the search terms or the scope rule is a new version, never an edit of this row.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
