-- Migration 055: ingest@1.7.0, the PR #22 owner decisions of 2026-09-29 on
-- text retention (ADR 0001, "Decisions of 2026-09-29 (PR #22 review)").
--
-- GUARDIAN: Jennifer McKinney, verbatim "Use normal retention". The
--   Guardian's 24-hour blanking, applied by analogy with ruling 9 in
--   ingest@1.6.0, is withdrawn; Guardian text follows the §19 detail window.
--   Posts already blanked stay blanked (nothing is restored or edited).
-- G3: a platform-terms blanking deletes the post's embedding in the same
--   transaction (src/collectors/retention.js); scores and audit rows stay.
--
-- New row only: ingest@1.6.0 keeps its row. No data is changed here.
--
-- The INSERT below is generated by:
--   node scripts/generate-methodology-migration.js ingest@1.7.0
-- and mirrors src/config/methodology-registry.js FIELD FOR FIELD.

-- ingest@1.7.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'ingest',
    '1.7.0',
    'pulse-ingest-v1',
    $cfg${
    "pii_fields_removed": [
        "author",
        "author_fullname",
        "author_id",
        "authors",
        "username",
        "user",
        "user_id",
        "screen_name",
        "creator",
        "uploader",
        "owner",
        "email"
    ],
    "collector_payload": "collectors build the stored payload from an allowlist of content fields; identity fields are never requested",
    "text_redaction": {
        "email_addresses": "[email]",
        "at_handles": "@[user]",
        "at_handle_min_length": 1,
        "reddit_user_handles": "u/[user] (u/<name> and /u/<name>); a scheme-less reddit.com/u/ or /user/ link becomes [profile link]",
        "phone_numbers": "[phone] (E.164 and NANP)",
        "identity_links": "[profile link]",
        "cc_names": "cc [name]",
        "trailing_signoffs": "removed",
        "wikipedia_unsigned": "removed"
    },
    "identity_links": "links that point at a person (/user/, /u/, /profile/, /@name, github.com/<user>, gitlab.com/<user>, x.com and twitter.com handles, linkedin.com/in/, medium.com/<name>, a <name>.substack.com root, facebook, instagram, t.me, YouTube channels, Wikipedia User pages) are not stored and are replaced in text",
    "privacy_claim": "identity fields are never stored; e-mail addresses, handles (including Reddit u/ names), phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content",
    "external_ids": "the upstream id is stored only when it is not identity-bearing (numeric, arXiv, PMID, DOI, HN item ids, Reddit t3_ fullnames, clean slugs); otherwise its keyed fingerprint is stored; the Telegram chat id is fingerprinted",
    "provenance": "HMAC-SHA256(PROVENANCE_KEY or AUDIT_HASH_KEY, source_slug + \":\" + raw upstream id + \":\" + canonical source URL), stored per post; reproduced by npm run verify-provenance -- --post <id> --url <original>",
    "location_granularity": "city",
    "location_basis": [
        "content",
        "publisher"
    ],
    "dedup_strategy": "unique (source, external id); sha256-content-hash join key",
    "legal_basis": "GDPR Article 6(1)(f) - Legitimate Interest",
    "payload_text_keys_not_stored": [
        "text",
        "title",
        "body",
        "content",
        "selftext"
    ],
    "text_storage": "the post text is stored once, in raw_posts.content; raw_payload keeps metadata only (url, published_at, location_basis, route, licence, attribution)",
    "collected_log": "every stored post writes a data_retention_log row, action collected, legal basis GDPR Article 6(1)(f), in the same statement as the insert",
    "text_retention": {
        "rule": "after its source's window the text is replaced by a removal notice (raw_posts.text_removed_at); scores and audit rows are kept (ADR 0001 ruling 9, \"Blank text, keep audit rows\"); for a platform-terms window the post's embedding (post_embeddings) is deleted in the same transaction (PR #22 decision G3)",
        "platform_terms_hours": {
            "reddit": 48,
            "youtube": 720,
            "tiktok": 720
        },
        "default": "RETENTION_DETAIL_DAYS (90) days, TECHNICAL_SPEC §19",
        "applied_by_analogy": [
            "youtube",
            "tiktok"
        ],
        "embeddings_on_platform_blanking": "deleted with the text (PR #22 decision G3, Jennifer McKinney 2026-09-29)",
        "rulings": {
            "guardian": "Jennifer McKinney, 2026-09-29, verbatim \"Use normal retention\": the Guardian takes the default §19 detail window; its 24-hour blanking by analogy (ingest@1.6.0) is withdrawn",
            "g3": "Jennifer McKinney, 2026-09-29: delete the embeddings when the text is blanked, for any source under platform-terms blanking; scores and audit rows stay (ruling 9)"
        }
    }
}$cfg$::jsonb,
    $just$ingest@1.7.0 records two owner decisions of 2026-09-29 from the PR #22 review. First, the Guardian: Jennifer ruled, verbatim, "Use normal retention", so the 24-hour blanking that ingest@1.6.0 applied to the Guardian by analogy with ruling 9 is withdrawn and Guardian text follows the §19 detail window (90 days) like every source without a platform-terms window; posts already blanked under the old window stay blanked and their receipts say so. Second, decision G3: when a platform-terms window (Reddit 48 hours, YouTube and TikTok 30 days) or an upstream deletion blanks a post's text, the post's embedding is deleted in the same transaction, because it is derived from the text; the scores, audit rows, content hash and provenance fingerprint are still kept (ruling 9). The detail window leaves embeddings to monthly compaction. Everything else is as in ingest@1.6.0.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
