-- Migration 060: the rolling 24 h bias window (bias@1.5.0) — PR #22
-- decision G2, approved by Jennifer McKinney on 2026-09-29 (ADR 0001).
--
-- The per-cycle fairness checks (src/pipeline/bias.js) run over the posts of
-- one 2–3 minute collection cycle, which rarely reaches bias@1.4.0's minimum
-- samples (principal #11). The SAME checks now ALSO run over every post
-- whose sentiment decision was recorded in the last 24 hours, daily (the
-- maintenance `daily` task) and on demand (`npm run bias:window`)
-- (src/pipeline/bias-window.js). Per-cycle checks are unchanged.
--
-- 1. bias_window_runs: one row per window run (when, which window, which
--    bias version, how it ended). Only its own status transition
--    (running -> completed | failed) is ever written after the insert.
-- 2. bias_window_assessments: one row per check per window run, the same
--    columns as bias_assessments. Append-only (the trigger function of
--    migration 036).
-- 3. bias@1.5.0 is registered (generated by
--      node scripts/generate-methodology-migration.js bias@1.5.0
--    and mirroring src/config/methodology-registry.js field for field).
--
-- Additive and idempotent: no existing row is updated or deleted.

CREATE TABLE IF NOT EXISTS bias_window_runs (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    window_hours            INTEGER NOT NULL CHECK (window_hours > 0),
    window_start            TIMESTAMPTZ NOT NULL,
    window_end              TIMESTAMPTZ NOT NULL,
    triggered_by            TEXT NOT NULL CHECK (triggered_by IN ('schedule', 'on_demand')),
    status                  TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
    methodology_version_id  UUID NOT NULL REFERENCES methodology_versions(id),
    posts_assessed          INTEGER,
    violations_found        INTEGER,
    error_details           TEXT,
    started_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at            TIMESTAMPTZ,
    CHECK (window_end > window_start)
);

CREATE INDEX IF NOT EXISTS idx_bias_window_runs_started ON bias_window_runs(started_at DESC);

CREATE TABLE IF NOT EXISTS bias_window_assessments (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    window_run_id           UUID NOT NULL REFERENCES bias_window_runs(id),
    assessment_type         TEXT NOT NULL,
    group_field             TEXT NOT NULL,
    group_value             TEXT NOT NULL,
    metric_name             TEXT NOT NULL,
    metric_value            REAL NOT NULL,
    threshold               REAL NOT NULL,
    is_violation            BOOLEAN NOT NULL DEFAULT FALSE,
    severity                TEXT,
    evidence                JSONB,
    methodology_version_id  UUID NOT NULL REFERENCES methodology_versions(id),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bias_window_assessments_run ON bias_window_assessments(window_run_id);
CREATE INDEX IF NOT EXISTS idx_bias_window_assessments_created ON bias_window_assessments(created_at DESC);

DROP TRIGGER IF EXISTS bias_window_assessments_append_only ON bias_window_assessments;
CREATE TRIGGER bias_window_assessments_append_only BEFORE UPDATE OR DELETE ON bias_window_assessments
    FOR EACH ROW EXECUTE FUNCTION forbid_append_only_change();

-- bias@1.5.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'bias',
    '1.5.0',
    'pulse-bias-monitor-v1',
    $cfg${
    "location_concentration_max": 0.35,
    "platform_parity_max_diff": 0.3,
    "negative_dominance_max": 0.6,
    "layer_names": {
        "location_concentration": "Location concentration",
        "platform_sentiment_parity": "Demographic parity",
        "negative_dominance": "Negative dominance"
    },
    "layer_notes": {
        "platform_sentiment_parity": "parity measured across source categories (platform), not user demographics; only categories with at least 10 posts in the job are compared",
        "location_concentration": "content-located posts only (publisher-located posts are a separate layer, ADR 0001 D3); needs at least 30 of them, else \"insufficient sample\" and no alert",
        "negative_dominance": "needs at least 30 posts in the job, else \"insufficient sample\" and no alert"
    },
    "citations": {
        "location_concentration": "Suresh & Guttag (2021)",
        "platform_sentiment_parity": "Barocas & Selbst (2016)",
        "negative_dominance": "Suresh & Guttag (2021)"
    },
    "planned_layers": [
        {
            "id": "equalized_odds",
            "name": "Equalized odds",
            "citation": "Hardt et al. (2016)",
            "note": "Phase 3 — not yet enforced"
        },
        {
            "id": "counterfactual_fairness",
            "name": "Counterfactual fairness",
            "citation": "Kusner et al. (2017)",
            "note": "Phase 3 — not yet enforced"
        }
    ],
    "layer_order": [
        "platform_sentiment_parity",
        "equalized_odds",
        "counterfactual_fairness"
    ],
    "legal_basis": "EU AI Act Article 13 - Transparency and provision of information",
    "location_basis_excluded": [
        "publisher"
    ],
    "location_concentration_scope": "posts located by their content (location_basis content, or no basis recorded); posts placed at the publisher's home city (location_basis publisher) are excluded and counted in the evidence",
    "location_min_sample": 30,
    "location_min_sample_rule": "fewer than 30 content-located posts in the job: the assessment is recorded as \"insufficient sample\" with its share stated, no violation and no alert",
    "parity_min_per_category": 10,
    "negative_min_sample": 30,
    "sample_rules": {
        "location_concentration": "at least 30 content-located posts in the job (location_min_sample), publisher-located posts excluded",
        "platform_sentiment_parity": "only categories with at least 10 posts are compared (parity_min_per_category); fewer than two such categories: insufficient sample",
        "negative_dominance": "at least 30 posts in the job (negative_min_sample)",
        "below_minimum": "\"insufficient sample\": the value is stated, no violation, no alert",
        "basis": "n >= 30 is the conventional minimum for treating a sample proportion as approximately normal (central limit theorem rule of thumb); n >= 10 per group is the conventional floor for comparing group means. Both are deliberately conservative floors, not significance tests."
    },
    "rolling_window": {
        "hours": 24,
        "schedule": "daily (maintenance task \"daily\") and on demand (npm run bias:window)",
        "scope": "every post whose sentiment decision was recorded in the 24 hours before the run",
        "checks": [
            "location_concentration",
            "platform_sentiment_parity",
            "negative_dominance"
        ],
        "rules": "the per-cycle thresholds and minimum samples (sample_rules), applied to the window instead of one cycle",
        "per_cycle": "the per-cycle checks still run after every collection cycle, unchanged",
        "decision": "PR #22 G2, approved by Jennifer McKinney 2026-09-29 (ADR 0001)"
    },
    "insufficient_sample_reporting": "the share of \"insufficient sample\" assessments per check (per cycle over the last 24 hours and 7 days; rolling window: the latest run and the last 7 days) is served by GET /api/bias/latest and GET /api/health"
}$cfg$::jsonb,
    $just$bias@1.5.0 adds a rolling 24-hour window to the fairness checks (PR #22 decision G2, approved by Jennifer McKinney on 2026-09-29). The per-cycle checks run over the posts scored in one 2–3 minute collection cycle, which rarely reaches bias@1.4.0's minimum samples (30 content-located posts, 10 posts per category, 30 posts), so the monitor could report "insufficient sample" indefinitely. The same three checks (location concentration and negative dominance, Suresh & Guttag 2021; platform sentiment parity, Barocas & Selbst 2016) now ALSO run once a day and on demand over every post whose sentiment decision was recorded in the previous 24 hours, with the same thresholds and minimum samples, so the minimums are reachable. Each window run is recorded in bias_window_runs and its assessments in bias_window_assessments, linked to this version; a violation raises an alert like a per-cycle one. The per-cycle checks are unchanged. The share of "insufficient sample" assessments per check is reported by GET /api/bias/latest and GET /api/health, so a monitor that never reaches its minimum is visible. Thresholds, names, citations and planned layers are as in bias@1.1.0 (AI Act Article 13).$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
