-- Migration 061: bias@1.6.0 — a platform-parity "insufficient sample"
-- assessment states its computed value (audit drift D-2, 2026-09-30).
--
-- bias@1.4.0 and bias@1.5.0 register that an assessment below its minimum
-- sample is recorded as "insufficient sample" with its value stated
-- (sample_rules.below_minimum). The platform sentiment parity check recorded
-- metric_value 0 on those rows instead. bias@1.6.0 records the largest
-- pairwise gap in average comparative sentiment across ALL the job's
-- categories (0 with fewer than two), still with no violation and no alert
-- (src/pipeline/bias.js, config key parity_insufficient_value). Everything
-- else is bias@1.5.0.
--
-- 1. Released rows are never edited: bias@1.4.0 and bias@1.5.0 each get an
--    erratum (methodology_errata, migration 030), mirroring
--    src/config/methodology-registry.js METHODOLOGY_ERRATA field for field;
--    a no-op when the corrected row is not registered. Their recorded
--    assessments are kept as they ran.
-- 2. bias@1.6.0 is registered (generated by
--      node scripts/generate-methodology-migration.js bias@1.6.0
--    and mirroring the registry field for field). It is inserted LAST, so
--    the file ends with exactly the generated row.
--
-- Additive and idempotent: no existing row is updated or deleted.

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'bias-1.4.0-parity-insufficient-value', 'bias@1.6.0', $err$bias@1.4.0 registers that an assessment below its minimum sample is recorded as "insufficient sample" with its value stated. The platform sentiment parity check did not do that: its "insufficient sample" rows (fewer than two categories with at least 10 posts) recorded metric_value 0, not the computed gap between categories. Read those rows as "insufficient sample, value not recorded"; the category averages are in the row's evidence. Location concentration and negative dominance did state their values. bias@1.6.0 records the gap. The bias@1.4.0 row is kept unedited as it was registered. Found by the documentation audit (drift D-2); recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'bias' AND mv.version = '1.4.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'bias-1.5.0-parity-insufficient-value', 'bias@1.6.0', $err$bias@1.5.0 registers that an assessment below its minimum sample is recorded as "insufficient sample" with its value stated. The platform sentiment parity check did not do that: its "insufficient sample" rows (fewer than two categories with at least 10 posts) recorded metric_value 0, not the computed gap between categories. Read those rows as "insufficient sample, value not recorded"; the category averages are in the row's evidence. Location concentration and negative dominance did state their values. bias@1.6.0 records the gap. The bias@1.5.0 row is kept unedited as it was registered. Found by the documentation audit (drift D-2); recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'bias' AND mv.version = '1.5.0'
ON CONFLICT (erratum_key) DO NOTHING;

-- bias@1.6.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'bias',
    '1.6.0',
    'pulse-bias-monitor-v1',
    $cfg${
    "location_concentration_max": 0.35,
    "platform_parity_max_diff": 0.3,
    "negative_dominance_max": 0.6,
    "layer_names": {
        "location_concentration": "Location concentration",
        "platform_sentiment_parity": "Demographic parity",
        "negative_dominance": "Negative dominance"
    },
    "layer_notes": {
        "platform_sentiment_parity": "parity measured across source categories (platform), not user demographics; only categories with at least 10 posts in the job are compared",
        "location_concentration": "content-located posts only (publisher-located posts are a separate layer, ADR 0001 D3); needs at least 30 of them, else \"insufficient sample\" and no alert",
        "negative_dominance": "needs at least 30 posts in the job, else \"insufficient sample\" and no alert"
    },
    "citations": {
        "location_concentration": "Suresh & Guttag (2021)",
        "platform_sentiment_parity": "Barocas & Selbst (2016)",
        "negative_dominance": "Suresh & Guttag (2021)"
    },
    "planned_layers": [
        {
            "id": "equalized_odds",
            "name": "Equalized odds",
            "citation": "Hardt et al. (2016)",
            "note": "Phase 3 — not yet enforced"
        },
        {
            "id": "counterfactual_fairness",
            "name": "Counterfactual fairness",
            "citation": "Kusner et al. (2017)",
            "note": "Phase 3 — not yet enforced"
        }
    ],
    "layer_order": [
        "platform_sentiment_parity",
        "equalized_odds",
        "counterfactual_fairness"
    ],
    "legal_basis": "EU AI Act Article 13 - Transparency and provision of information",
    "location_basis_excluded": [
        "publisher"
    ],
    "location_concentration_scope": "posts located by their content (location_basis content, or no basis recorded); posts placed at the publisher's home city (location_basis publisher) are excluded and counted in the evidence",
    "location_min_sample": 30,
    "location_min_sample_rule": "fewer than 30 content-located posts in the job: the assessment is recorded as \"insufficient sample\" with its share stated, no violation and no alert",
    "parity_min_per_category": 10,
    "negative_min_sample": 30,
    "sample_rules": {
        "location_concentration": "at least 30 content-located posts in the job (location_min_sample), publisher-located posts excluded",
        "platform_sentiment_parity": "only categories with at least 10 posts are compared (parity_min_per_category); fewer than two such categories: insufficient sample, stating the largest pairwise gap in average comparative sentiment across all the job's categories (0 when it has fewer than two)",
        "negative_dominance": "at least 30 posts in the job (negative_min_sample)",
        "below_minimum": "\"insufficient sample\": the value is stated, no violation, no alert",
        "basis": "n >= 30 is the conventional minimum for treating a sample proportion as approximately normal (central limit theorem rule of thumb); n >= 10 per group is the conventional floor for comparing group means. Both are deliberately conservative floors, not significance tests."
    },
    "rolling_window": {
        "hours": 24,
        "schedule": "daily (maintenance task \"daily\") and on demand (npm run bias:window)",
        "scope": "every post whose sentiment decision was recorded in the 24 hours before the run",
        "checks": [
            "location_concentration",
            "platform_sentiment_parity",
            "negative_dominance"
        ],
        "rules": "the per-cycle thresholds and minimum samples (sample_rules), applied to the window instead of one cycle",
        "per_cycle": "the per-cycle checks still run after every collection cycle, unchanged",
        "decision": "PR #22 G2, approved by Jennifer McKinney 2026-09-29 (ADR 0001)"
    },
    "insufficient_sample_reporting": "the share of \"insufficient sample\" assessments per check (per cycle over the last 24 hours and 7 days; rolling window: the latest run and the last 7 days) is served by GET /api/bias/latest and GET /api/health",
    "parity_insufficient_value": "max_diff_all_categories",
    "changelog": [
        "bias@1.6.0 (audit drift D-2, 2026-09-30): a platform-parity \"insufficient sample\" assessment states its computed value (the largest pairwise gap across all categories, small ones included) instead of 0, as sample_rules.below_minimum registered since bias@1.4.0; no violation and no alert, as before"
    ]
}$cfg$::jsonb,
    $just$bias@1.6.0 makes the platform sentiment parity check (Barocas & Selbst 2016) do what bias@1.4.0 and bias@1.5.0 registered for every check below its minimum sample: "the value is stated". When fewer than two source categories have at least 10 posts in the job, the assessment is still recorded as "insufficient sample" with no violation and no alert, but its value is now the largest pairwise difference in average comparative sentiment across all of the job's categories, small ones included (0 when the job has fewer than two categories), with the pair named in the evidence. Until now the check recorded 0 there, so a reader could not tell a small gap from a large one. Location concentration and negative dominance already stated their values. Assessments recorded under bias@1.4.0 and bias@1.5.0 are kept as they ran (0); an erratum on each of those versions records the difference. Thresholds, minimum samples, the rolling 24-hour window, names, citations and planned layers are as in bias@1.5.0 (AI Act Article 13).$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
