-- Migration 065: embedding@1.1.0 — sentence-transformers 2.7.0 -> 6.1.0 with the
-- same model and pinned revision (Dependabot #29; Jennifer McKinney
-- 2026-09-30: "Adopt as embedding@1.1.0").
--
-- The embeddings service (python/embeddings_service.py, image python/Dockerfile)
-- now installs sentence-transformers 6.1.0, transformers 5.18.0,
-- huggingface_hub 1.33.0 and tokenizers 0.23.2 (torch stays 2.12.1+cpu;
-- python/requirements-service.in and the hash lock requirements-service.txt).
-- The library is part of the embedding methodology (config.library), so the
-- bump ships as a NEW version row; embedding@1.0.0 (migration 012) is never
-- edited. Evidence: 12 test texts embedded with 2.7.0 and 6.1.0 on macOS
-- arm64 and in the image on linux/arm64 and linux/amd64 gave bit-identical
-- vectors (config.equivalence), so embedding@1.0.0 vectors stay comparable
-- and are not re-embedded.
--
-- src/pipeline/embeddings.js records the LAST embedding row of
-- src/config/methodology-registry.js on every new vector
-- (post_embeddings.methodology_version), which is now 1.1.0. Vectors stored
-- earlier keep '1.0.0'.
--
-- Generated by
--   node scripts/generate-methodology-migration.js embedding@1.1.0
-- and mirroring the registry field for field
-- (tests/unit/pure/methodologyRegistry.test.js). Additive and idempotent: no
-- existing row is updated or deleted.

-- embedding@1.1.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'embedding',
    '1.1.0',
    'sentence-transformers/all-MiniLM-L6-v2',
    $cfg${
    "revision": "1110a243fdf4706b3f48f1d95db1a4f5529b4d41",
    "dimensions": 384,
    "normalize_embeddings": true,
    "library": "sentence-transformers==6.1.0",
    "service": "python/embeddings_service.py",
    "revision_env": "EMBED_MODEL_REVISION",
    "library_dependencies": {
        "transformers": "5.18.0",
        "huggingface_hub": "1.33.0",
        "tokenizers": "0.23.2",
        "torch": "2.12.1+cpu"
    },
    "lock": "python/requirements-service.txt (pip-compile --generate-hashes, installed with --require-hashes)",
    "equivalence": {
        "compared_with": "embedding@1.0.0 (sentence-transformers 2.7.0, transformers 4.57.6, huggingface_hub 0.36.2, tokenizers 0.22.2), same torch build on each platform",
        "texts": 12,
        "result": "bit-identical float32 vectors (normalised and raw), identical token ids; max abs difference 0, minimum cosine 1.0",
        "platforms": [
            "macOS arm64 (virtualenv)",
            "linux/arm64 (embeddings image)",
            "linux/amd64 (embeddings image, emulated)"
        ]
    },
    "changelog": [
        "embedding@1.1.0 (Dependabot #29, 2026-09-30): sentence-transformers 2.7.0 -> 6.1.0 with transformers 5.18.0, huggingface_hub 1.33.0 and tokenizers 0.23.2; same model, revision, dimensions and normalisation; vectors bit-identical to embedding@1.0.0 on the comparison set"
    ]
}$cfg$::jsonb,
    $just$embedding@1.1.0 moves the embeddings service from sentence-transformers 2.7.0 to 6.1.0, which brings transformers 5.18.0, huggingface_hub 1.33.0 and tokenizers 0.23.2 (torch stays 2.12.1+cpu). The model is the same all-MiniLM-L6-v2 (Reimers & Gurevych 2019) at the same pinned Hugging Face commit, with 384 dimensions and L2 normalisation, so cosine similarity is still a dot product. The library is part of the methodology because a new version could change the vectors; it was therefore compared before adoption: 12 test texts (English, French, Chinese, an emoji line, an empty string, a single character and a text longer than the 256-token limit, which exercises truncation) were embedded with both versions on macOS arm64, and inside the embeddings image on linux/arm64 and linux/amd64, each version against its own torch build of that platform. On every platform the vectors were bit-identical (maximum absolute difference 0, minimum cosine similarity 1.0), normalised and raw, and the token ids were identical. Vectors recorded under embedding@1.0.0 therefore stay directly comparable with new ones and are not re-embedded. New vectors record embedding@1.1.0; the embedding@1.0.0 row is kept unedited.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
