-- Migration 066: ingest@1.8.0 and audit_narration@1.4.0 — the content hash
-- is not a join key (wording only; Jennifer McKinney 2026-09-30, verbatim
-- "Register new versions (Recommended)").
--
-- Every released ingest row (1.0.0 to 1.7.0) describes the SHA-256 content
-- hash as a join key: "the immutable join key" in the justification and,
-- from 1.1.0, "sha256-content-hash join key" in config.dedup_strategy. The
-- receipt's ingestion step (audit_narration@1.3.0, researcher view) said the
-- hash "is the immutable join key across the decision audit log". No query
-- joins, reads or deduplicates on raw_posts.content_hash. What it is:
--   - src/pipeline/ingest.js writes SHA-256(stored, normalised text) once;
--   - the sentiment, relevance and discourse steps record the same digest of
--     the text they scored as decision_audit_log.input_hash;
--   - src/audit/replay.js (npm run replay) re-hashes the stored text against
--     input_hash; src/routes/audit.js serves input_hash only HMAC-keyed;
--   - duplicates are dropped by UNIQUE (source_id, external_id) alone.
--
-- No behaviour change: no column, index, query or stored value changes.
--
-- 1. Released rows are never edited: ingest@1.0.0 to ingest@1.7.0 each get an
--    erratum (methodology_errata, migration 030), mirroring
--    src/config/methodology-registry.js METHODOLOGY_ERRATA field for field;
--    each is a no-op when the corrected row is not registered. Posts keep
--    the ingest version they were stored under (raw_posts.ingest_mv_id).
-- 2. ingest@1.8.0 and audit_narration@1.4.0 are registered (generated by
--      node scripts/generate-methodology-migration.js ingest@1.8.0 audit_narration@1.4.0
--    and mirroring the registry field for field). They are inserted LAST,
--    so the file ends with exactly the generated rows. Both are the last
--    registry entries of their component, so the collection runner stamps
--    new posts with ingest@1.8.0 (src/pipeline/methodology.js) and the
--    receipt reports audit_narration@1.4.0 (src/config/audit-narration.js).
--
-- Additive and idempotent: no existing row is updated or deleted.

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.0.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.0.0 describes the SHA-256 content hash as a join key and registers "sha256-content-hash" as its deduplication strategy. That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.0.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.0.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.1.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.1.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.1.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.1.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.2.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.2.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.2.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.2.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.3.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.3.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.3.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.3.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.4.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.4.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.4.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.4.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.5.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.5.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.5.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.5.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.6.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.6.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.6.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.6.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'ingest-1.7.0-content-hash-wording', 'ingest@1.8.0', $err$ingest@1.7.0 describes the SHA-256 content hash as a join key ("sha256-content-hash join key"). That wording is wrong; nothing ran differently. No query joins, reads or deduplicates on the content hash (raw_posts.content_hash): duplicates were dropped by unique (source, external id) alone. The hash is the SHA-256 of the stored post text after normalisation and redaction; the sentiment, relevance and discourse steps record the same digest of the text they scored as input_hash in the decision audit log, which `npm run replay` re-checks against the stored text. ingest@1.8.0 registers the corrected wording. The ingest@1.7.0 row is kept unedited as it was registered, and posts stored under it keep their version. Found by the documentation audit; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'ingest' AND mv.version = '1.7.0'
ON CONFLICT (erratum_key) DO NOTHING;

-- ingest@1.8.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'ingest',
    '1.8.0',
    'pulse-ingest-v1',
    $cfg${
    "pii_fields_removed": [
        "author",
        "author_fullname",
        "author_id",
        "authors",
        "username",
        "user",
        "user_id",
        "screen_name",
        "creator",
        "uploader",
        "owner",
        "email"
    ],
    "collector_payload": "collectors build the stored payload from an allowlist of content fields; identity fields are never requested",
    "text_redaction": {
        "email_addresses": "[email]",
        "at_handles": "@[user]",
        "at_handle_min_length": 1,
        "reddit_user_handles": "u/[user] (u/<name> and /u/<name>); a scheme-less reddit.com/u/ or /user/ link becomes [profile link]",
        "phone_numbers": "[phone] (E.164 and NANP)",
        "identity_links": "[profile link]",
        "cc_names": "cc [name]",
        "trailing_signoffs": "removed",
        "wikipedia_unsigned": "removed"
    },
    "identity_links": "links that point at a person (/user/, /u/, /profile/, /@name, github.com/<user>, gitlab.com/<user>, x.com and twitter.com handles, linkedin.com/in/, medium.com/<name>, a <name>.substack.com root, facebook, instagram, t.me, YouTube channels, Wikipedia User pages) are not stored and are replaced in text",
    "privacy_claim": "identity fields are never stored; e-mail addresses, handles (including Reddit u/ names), phone numbers, sign-offs and profile links in text are redacted; free text may still contain names mentioned in content",
    "external_ids": "the upstream id is stored only when it is not identity-bearing (numeric, arXiv, PMID, DOI, HN item ids, Reddit t3_ fullnames, clean slugs); otherwise its keyed fingerprint is stored; the Telegram chat id is fingerprinted",
    "provenance": "HMAC-SHA256(PROVENANCE_KEY or AUDIT_HASH_KEY, source_slug + \":\" + raw upstream id + \":\" + canonical source URL), stored per post; reproduced by npm run verify-provenance -- --post <id> --url <original>",
    "location_granularity": "city",
    "location_basis": [
        "content",
        "publisher"
    ],
    "dedup_strategy": "unique (source, external id): a post whose source and upstream id are already stored is not stored again; the content hash plays no part in deduplication",
    "legal_basis": "GDPR Article 6(1)(f) - Legitimate Interest",
    "payload_text_keys_not_stored": [
        "text",
        "title",
        "body",
        "content",
        "selftext"
    ],
    "text_storage": "the post text is stored once, in raw_posts.content; raw_payload keeps metadata only (url, published_at, location_basis, route, licence, attribution)",
    "collected_log": "every stored post writes a data_retention_log row, action collected, legal basis GDPR Article 6(1)(f), in the same statement as the insert",
    "text_retention": {
        "rule": "after its source's window the text is replaced by a removal notice (raw_posts.text_removed_at); scores and audit rows are kept (ADR 0001 ruling 9, \"Blank text, keep audit rows\"); for a platform-terms window the post's embedding (post_embeddings) is deleted in the same transaction (PR #22 decision G3)",
        "platform_terms_hours": {
            "reddit": 48,
            "youtube": 720,
            "tiktok": 720
        },
        "default": "RETENTION_DETAIL_DAYS (90) days, TECHNICAL_SPEC §19",
        "applied_by_analogy": [
            "youtube",
            "tiktok"
        ],
        "embeddings_on_platform_blanking": "deleted with the text (PR #22 decision G3, Jennifer McKinney 2026-09-29)",
        "rulings": {
            "guardian": "Jennifer McKinney, 2026-09-29, verbatim \"Use normal retention\": the Guardian takes the default §19 detail window; its 24-hour blanking by analogy (ingest@1.6.0) is withdrawn",
            "g3": "Jennifer McKinney, 2026-09-29: delete the embeddings when the text is blanked, for any source under platform-terms blanking; scores and audit rows stay (ruling 9)"
        }
    },
    "content_hash": "SHA-256 of the stored post text (after normalisation and redaction), written once at ingest to raw_posts.content_hash and kept when the text is removed (ruling 9); the sentiment, relevance and discourse steps record the same digest of the text they scored as decision_audit_log.input_hash, which npm run replay re-checks against the stored text and GET /api/audit serves only keyed (HMAC-SHA256 with AUDIT_HASH_KEY); an integrity check, not a join key: no query joins, reads or deduplicates on it",
    "changelog": [
        "ingest@1.8.0 (2026-09-30): wording-only correction; the content hash is described as what it is (an integrity check recorded as input_hash), not as a join key; no behaviour change"
    ]
}$cfg$::jsonb,
    $just$ingest@1.8.0 corrects wording only: the code, the stored data and every rule are exactly as in ingest@1.7.0. Every earlier ingest version described the SHA-256 content hash as a join key ("the immutable join key", and in its config "sha256-content-hash join key"). It is not one: no query joins, reads or deduplicates on it. What it is: the SHA-256 of the stored post text, after normalisation and redaction, written once at ingest (raw_posts.content_hash) and kept when the text is removed. The sentiment, relevance and discourse steps each record the same digest of the text they scored as input_hash in the decision audit log, so `npm run replay` can show that the stored text is the text that was scored; the audit API serves input_hash only keyed (HMAC-SHA256 with AUDIT_HASH_KEY), never raw. Duplicates are dropped by unique (source, external id) alone. Posts stored under earlier ingest versions keep their version; an erratum on each of those versions records this correction, and their rows are kept unedited. Everything else is as in ingest@1.7.0.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;

-- audit_narration@1.4.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'audit_narration',
    '1.4.0',
    'pulse-narration-templates-v1',
    $cfg${
    "audiences": [
        "public",
        "plain",
        "config",
        "researcher"
    ],
    "renderer": "src/config/audit-narration.js",
    "rendering": "read-time deterministic templates over stored decision_audit_log output + methodology config; no per-post prose is generated or persisted",
    "reproduce_command": "npm run replay -- --post {post_id}",
    "verify_provenance_command": "npm run verify-provenance -- --post {post_id} --url <original URL> [--id <original id>]",
    "ingest_branches": [
        "live_source",
        "demo_feed"
    ],
    "demo_source_type": "demo",
    "provenance_fields": [
        "source",
        "published_at",
        "permalink",
        "external_id",
        "fingerprint",
        "verifiable"
    ],
    "ingest_hash_note": "The stored text is SHA-256 hashed at ingest; each scoring step records the same digest of the text it scored as input_hash, which npm run replay re-checks against the stored text and this receipt serves only keyed (HMAC-SHA256 with AUDIT_HASH_KEY). It is an integrity check, not a join key.",
    "changelog": [
        "audit_narration@1.4.0 (2026-09-30): wording-only correction of the ingestion step's researcher view; the content hash is described as an integrity check recorded as input_hash, not as a join key"
    ]
}$cfg$::jsonb,
    $just$The audit endpoint serves four audience representations (public, journalist, regulator, researcher) of every decision step. The wording is part of the auditable surface, so the template set is registered here and version-bumped on any change. 1.4.0 corrects wording only, in the researcher view of the ingestion step (real sources and demo feeds alike): it no longer says that the content hash is "the immutable join key across the decision audit log". It now says what the hash is: the stored text is SHA-256 hashed at ingest; each scoring step records the same digest of the text it scored as input_hash, which npm run replay re-checks against the stored text and the audit API serves only keyed (HMAC-SHA256 with AUDIT_HASH_KEY); it is an integrity check, not a join key. No stored data, score or rule changes. Every other sentence of every step is unchanged from 1.3.0.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
