-- Migration 067: audit_narration@1.5.0 — the relevance receipt tells the
-- truth about today's totals (wording only; relevance-accuracy Stage 0, P0).
--
-- Decision D1, Jennifer McKinney 2026-09-30, verbatim "Count only
-- AI-relevant (Recommended)": totals will count only AI-relevant posts. That
-- switch ships with the NEXT relevance version (the Stage-1 lexicon), after
-- its gold-set gate: under relevance@1.2.0 many posts from AI-specific feeds
-- match no term, so switching now would drop real AI posts.
--
-- Until then the receipt must say what is true. Every released narration
-- (audit_narration@1.1.0 to 1.4.0, src/config/audit-narration.js
-- renderRelevance) told the public that a post with no AI term "does not
-- count toward AI-discourse totals", and that a matched post counts "because
-- it's clearly talking about AI". No aggregate query filters on
-- relevance_results (posts, sentiment, sources/timeseries, health, query,
-- compaction rollups): every stored post counts, whatever its score; the
-- score gates only embedding (relevance@1.2.0 embed_gate_min_score).
--
-- No behaviour change: no column, index, query or stored value changes.
--
-- 1. Released rows are never edited: audit_narration@1.1.0 to 1.4.0 each get
--    an erratum (methodology_errata, migration 030), mirroring
--    src/config/methodology-registry.js METHODOLOGY_ERRATA field for field;
--    each is a no-op when the corrected row is not registered.
-- 2. audit_narration@1.5.0 is registered (generated by
--      node scripts/generate-methodology-migration.js audit_narration@1.5.0
--    and mirroring the registry field for field). It is inserted LAST, so the
--    file ends with exactly the generated row. It is the last registry entry
--    of its component, so the receipt reports audit_narration@1.5.0
--    (src/config/audit-narration.js NARRATION_VERSION).
--
-- Additive and idempotent: no existing row is updated or deleted.

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'audit_narration-1.1.0-relevance-totals-wording', 'audit_narration@1.5.0', $err$audit_narration@1.1.0 told the public, in the relevance step, that a post which matched no AI topic term "does not count toward AI-discourse totals", and that a post which matched counts "because it's clearly talking about AI". That was not true: every stored post counted toward every total (the map, the time series and the category shares) whatever its relevance score; the score decided only whether the post was embedded (the matched terms also name the topic themes). Read receipts rendered under this version with that in mind; no stored data or score is affected. audit_narration@1.5.0 registers the corrected wording. Totals will count only AI-relevant posts from the next relevance version (decision D1, Jennifer McKinney 2026-09-30). The audit_narration@1.1.0 row is kept unedited as it was registered. Found by the relevance-accuracy review; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'audit_narration' AND mv.version = '1.1.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'audit_narration-1.2.0-relevance-totals-wording', 'audit_narration@1.5.0', $err$audit_narration@1.2.0 told the public, in the relevance step, that a post which matched no AI topic term "does not count toward AI-discourse totals", and that a post which matched counts "because it's clearly talking about AI". That was not true: every stored post counted toward every total (the map, the time series and the category shares) whatever its relevance score; the score decided only whether the post was embedded (the matched terms also name the topic themes). Read receipts rendered under this version with that in mind; no stored data or score is affected. audit_narration@1.5.0 registers the corrected wording. Totals will count only AI-relevant posts from the next relevance version (decision D1, Jennifer McKinney 2026-09-30). The audit_narration@1.2.0 row is kept unedited as it was registered. Found by the relevance-accuracy review; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'audit_narration' AND mv.version = '1.2.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'audit_narration-1.3.0-relevance-totals-wording', 'audit_narration@1.5.0', $err$audit_narration@1.3.0 told the public, in the relevance step, that a post which matched no AI topic term "does not count toward AI-discourse totals", and that a post which matched counts "because it's clearly talking about AI". That was not true: every stored post counted toward every total (the map, the time series and the category shares) whatever its relevance score; the score decided only whether the post was embedded (the matched terms also name the topic themes). Read receipts rendered under this version with that in mind; no stored data or score is affected. audit_narration@1.5.0 registers the corrected wording. Totals will count only AI-relevant posts from the next relevance version (decision D1, Jennifer McKinney 2026-09-30). The audit_narration@1.3.0 row is kept unedited as it was registered. Found by the relevance-accuracy review; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'audit_narration' AND mv.version = '1.3.0'
ON CONFLICT (erratum_key) DO NOTHING;

INSERT INTO methodology_errata (methodology_version_id, erratum_key, corrected_by, erratum)
SELECT mv.id, 'audit_narration-1.4.0-relevance-totals-wording', 'audit_narration@1.5.0', $err$audit_narration@1.4.0 told the public, in the relevance step, that a post which matched no AI topic term "does not count toward AI-discourse totals", and that a post which matched counts "because it's clearly talking about AI". That was not true: every stored post counted toward every total (the map, the time series and the category shares) whatever its relevance score; the score decided only whether the post was embedded (the matched terms also name the topic themes). Read receipts rendered under this version with that in mind; no stored data or score is affected. audit_narration@1.5.0 registers the corrected wording. Totals will count only AI-relevant posts from the next relevance version (decision D1, Jennifer McKinney 2026-09-30). The audit_narration@1.4.0 row is kept unedited as it was registered. Found by the relevance-accuracy review; recorded 2026-09-30.$err$
FROM methodology_versions mv
WHERE mv.component = 'audit_narration' AND mv.version = '1.4.0'
ON CONFLICT (erratum_key) DO NOTHING;

-- audit_narration@1.5.0
INSERT INTO methodology_versions (component, version, model_name, config, justification, effective_from)
VALUES (
    'audit_narration',
    '1.5.0',
    'pulse-narration-templates-v1',
    $cfg${
    "audiences": [
        "public",
        "plain",
        "config",
        "researcher"
    ],
    "renderer": "src/config/audit-narration.js",
    "rendering": "read-time deterministic templates over stored decision_audit_log output + methodology config; no per-post prose is generated or persisted",
    "reproduce_command": "npm run replay -- --post {post_id}",
    "verify_provenance_command": "npm run verify-provenance -- --post {post_id} --url <original URL> [--id <original id>]",
    "ingest_branches": [
        "live_source",
        "demo_feed"
    ],
    "demo_source_type": "demo",
    "provenance_fields": [
        "source",
        "published_at",
        "permalink",
        "external_id",
        "fingerprint",
        "verifiable"
    ],
    "ingest_hash_note": "The stored text is SHA-256 hashed at ingest; each scoring step records the same digest of the text it scored as input_hash, which npm run replay re-checks against the stored text and this receipt serves only keyed (HMAC-SHA256 with AUDIT_HASH_KEY). It is an integrity check, not a join key.",
    "changelog": [
        "audit_narration@1.5.0 (2026-09-30): wording-only correction of the relevance step's public view; every stored post counts toward the AI-discourse totals today, whatever its relevance score"
    ],
    "relevance_public": {
        "matched": "This post matched the AI topic list, and it counts toward the AI-discourse totals.",
        "no_match": "This post did not match the AI topic list. Today it still counts toward the AI-discourse totals; from the next relevance version, only AI-relevant posts will count."
    }
}$cfg$::jsonb,
    $just$The audit endpoint serves four audience representations (public, journalist, regulator, researcher) of every decision step. The wording is part of the auditable surface, so the template set is registered here and version-bumped on any change. 1.5.0 corrects wording only, in the public view of the relevance step. Every earlier version said that a post which matched no AI topic term "does not count toward AI-discourse totals", and that a post which matched counts "because it's clearly talking about AI". Neither was true: every stored post counts toward the totals (the map, the time series and the category shares) whatever its relevance score; the score decides only whether the post is embedded (the matched terms also name the topic themes). The public view now says that a post matched the AI topic list and counts toward the AI-discourse totals, or that it did not match and today still counts, and that from the next relevance version only AI-relevant posts will count (decision D1, Jennifer McKinney 2026-09-30: "Count only AI-relevant"). That switch waits for the next relevance version and its gold-set check, because many posts from AI-specific feeds match no term under relevance@1.2.0 and would be dropped. No stored data, score or rule changes. Every other sentence of every step is unchanged from 1.4.0; an erratum on each earlier audit_narration version records this correction.$just$,
    clock_timestamp()
)
ON CONFLICT (component, version) DO NOTHING;
