#!/usr/bin/env bash
# docs/diagrams/render.sh — keep every diagram's three artifacts in sync.
#
# For each Mermaid source docs/diagrams/**/<name>.mmd (the CANONICAL file):
#   <name>.html  is regenerated: it embeds the .mmd definition VERBATIM
#                (HTML-escaped inside <pre class="mermaid">; the browser
#                decodes it back to the identical text) and renders it with
#                Mermaid 11 and the forest theme;
#   <name>.png   is regenerated from the .mmd with @mermaid-js/mermaid-cli
#                (mmdc), the forest theme and mmdc-config.json (natural
#                width, useMaxWidth false), at scale 2, lowered to 1.5 or 1
#                if either dimension would reach 8000 px (the Claude API
#                image limit); the script fails if it still does.
#
#   bash docs/diagrams/render.sh            regenerate every .html and .png
#   bash docs/diagrams/render.sh a.mmd ...  only the given sources
#   bash docs/diagrams/render.sh --check    verify only: every .html embeds
#                                           its .mmd exactly, every .png
#                                           exists, is under 8000 px and is
#                                           not older than its .mmd
#
# Needs: bash, python3, and npx (Node) for mmdc. The first line of each
# .mmd is "%% Title: <title>"; the second is "%% Summary: <one sentence>".

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MMDC_VERSION="11.12.0"
MAX_PX=8000
CHECK=0
declare -a FILES=()

for arg in "$@"; do
    case "$arg" in
        --check) CHECK=1 ;;
        -h|--help) sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) FILES+=("$arg") ;;
    esac
done

if [[ ${#FILES[@]} -eq 0 ]]; then
    while IFS= read -r f; do FILES+=("$f"); done < <(find "$HERE" -name '*.mmd' | sort)
fi

# PNG width and height from the IHDR chunk.
png_size() {
    python3 -c 'import struct,sys; d=open(sys.argv[1],"rb").read(24); print(*struct.unpack(">II", d[16:24]))' "$1"
}

# Write <name>.html for <name>.mmd.
write_html() {
    python3 - "$1" "${1%.mmd}.html" <<'PY'
import html, sys
src, out = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8").read()
lines = text.splitlines()
title = lines[0].split("Title:", 1)[1].strip() if lines and "Title:" in lines[0] else src
summary = lines[1].split("Summary:", 1)[1].strip() if len(lines) > 1 and "Summary:" in lines[1] else ""
name = src.rsplit("/", 1)[-1]
page = f"""<!DOCTYPE html>
<!--
  SYNC CONTRACT: {name} is the CANONICAL Mermaid source of this diagram.
  The <pre class="mermaid"> block below embeds that file's definition
  VERBATIM (HTML-escaped; the browser decodes it to the identical text),
  and the .png beside it is rendered from the same .mmd with mermaid-cli
  and the forest theme. Do not edit this file: edit the .mmd, then run
  bash docs/diagrams/render.sh.
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pulse of AI · {html.escape(title)}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
<style>
  body {{ margin: 0; padding: 32px 40px; background: #ffffff; color: #1b1f23;
         font-family: system-ui, -apple-system, "Segoe UI", sans-serif; }}
  h1 {{ font-size: 22px; margin: 0 0 6px; }}
  p.summary {{ margin: 0 0 8px; color: #57606a; font-size: 14px; }}
  p.source {{ margin: 0 0 24px; color: #57606a; font-size: 12px; }}
  pre.mermaid {{ background: none; border: none; margin: 0; }}
</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<p class="summary">{html.escape(summary)}</p>
<p class="source">Canonical source: <code>{html.escape(name)}</code> · index: <code>docs/diagrams/README.md</code></p>
<pre class="mermaid">
{html.escape(text, quote=False)}</pre>
<script>mermaid.initialize({{ startOnLoad: true, theme: 'forest', securityLevel: 'strict', maxTextSize: 200000 }});</script>
</body>
</html>
"""
open(out, "w", encoding="utf-8").write(page)
PY
}

# Exit non-zero unless <name>.html embeds <name>.mmd exactly.
check_html() {
    python3 - "$1" "${1%.mmd}.html" <<'PY'
import html, re, sys
src, out = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8").read()
page = open(out, encoding="utf-8").read()
m = re.search(r'<pre class="mermaid">\n(.*?)</pre>', page, re.S)
sys.exit(0 if m and html.unescape(m.group(1)) == text else 1)
PY
}

render_png() {
    local src="$1" png="${1%.mmd}.png" scale w h
    for scale in 2 1.5 1; do
        rm -f "$png"
        if ! npx -y "@mermaid-js/mermaid-cli@${MMDC_VERSION}" -q -i "$src" -o "$png" -t forest -b white -s "$scale" -c "$HERE/mmdc-config.json" >/dev/null \
            || [[ ! -f "$png" ]]; then
            echo "  mmdc failed for $src" >&2
            return 1
        fi
        read -r w h < <(png_size "$png")
        if (( w < MAX_PX && h < MAX_PX )); then
            echo "  ${png#"$HERE"/}  ${w}x${h} (scale $scale)"
            return 0
        fi
    done
    echo "  $png is ${w}x${h}: over ${MAX_PX}px even at scale 1 — split the diagram" >&2
    return 1
}

status=0
for src in "${FILES[@]}"; do
    [[ "$src" == /* ]] || src="$(pwd)/$src"
    rel="${src#"$HERE"/}"
    png="${src%.mmd}.png"
    if (( CHECK )); then
        problems=""
        check_html "$src" || problems+=" html-out-of-sync"
        if [[ ! -f "$png" ]]; then
            problems+=" png-missing"
        else
            read -r w h < <(png_size "$png")
            (( w < MAX_PX && h < MAX_PX )) || problems+=" png-${w}x${h}-too-large"
            [[ "$png" -nt "$src" || ! "$src" -nt "$png" ]] || problems+=" png-older-than-mmd"
        fi
        if [[ -n "$problems" ]]; then echo "FAIL $rel:$problems"; status=1; else echo "ok   $rel (${w}x${h})"; fi
    else
        echo "$rel"
        write_html "$src"
        render_png "$src" || status=1
    fi
done
exit $status
