#!/usr/bin/env node
// scripts/compact.js
// Monthly compaction job: moves Tier 1 (post-level detail) to Tier 2 (monthly rollups).
// Runs in the worker's repeatable `maintenance` job (src/workers/
// maintenance.worker.js, P10-2), or manually: node scripts/compact.js [YYYY-MM]
//
// What it does (P10-2: everything it logs is what it actually changed):
//   1. Identify every month that ENDS before the detail-window cutoff
//      (RETENTION_DETAIL_DAYS) and has real posts not yet compacted
//   2. Aggregate the month's real posts and scores into monthly_*_rollups
//   3. Remove any text still stored with the retention mechanism
//      (src/collectors/retention.js — content is NOT NULL, so it is replaced
//      by a notice and text_removed_at is set; the retention job normally
//      did this already at the end of each post's window)
//   4. Delete post_embeddings for the month's real posts (re-computable)
//   5. Write ONE data_retention_log row 'compacted' with the true counts
//   6. Write the compaction_log row
//
// Demo posts (P9-3): posts of data_sources.source_type = 'demo' are the
// standup's FICTIONAL population (scripts/populate.js).
//   - They are EXCLUDED from both rollups, so invented discourse never
//     enters the long-term Tier 2 record.
//   - At the retention boundary (collected_at older than
//     RETENTION_DETAIL_DAYS) they are DELETED outright, together with every
//     row that references them: the per-post score rows, their
//     decision_audit_log rows, their embeddings, and the demo feeds'
//     correlation sightings (plus any pseudonymous profile left with no
//     evidence at all). A profile that survives has its platform_count and
//     sighting window recomputed from its remaining sightings in the same
//     transaction. Each purge batch runs in its own transaction and
//     writes one data_retention_log row (action 'purged_demo').
//     The log row lists the purged post ids (reason.post_ids), so an embed
//     job queued before the purge completes as a no-op with that reason
//     instead of failing with "Post not found" (src/pipeline/embeddings.js),
//     and after each purge the pending embed jobs of the purged posts are
//     removed from the queue (src/queues/embed-cleanup.js).
//     Owner decision 2026-09-29: "Delete demo posts and their rows
//     (Recommended)". The source_type = 'demo' filter is enforced in the SQL
//     of EVERY delete, so real collected posts and their audit trails are
//     never touched, whatever a post's title, content or source name says.
//   - The purge runs BEFORE compaction, so a demo post is never compacted.

'use strict';

require('dotenv').config();
const { dbAll, dbTransaction, closePool } = require('../src/db/connection');
const { DEMO_SOURCE_TYPE, DEMO_PURGE_ACTION } = require('../src/config/data-mode');
const { getSource, retentionDetailDays } = require('../src/config/source-registry');
const { removeTextBatch } = require('../src/collectors/retention');

// M1: the detail window is read per call through the strict registry
// parser (src/config/source-registry.js retentionDetailDays): a bad
// RETENTION_DETAIL_DAYS throws before anything is purged or compacted.
const retentionDays = () => retentionDetailDays(process.env);

// Demo purge batch size: bounded so one transaction never holds locks on an
// unbounded set of rows. Clamped to [1, 5000]; default 500 posts per batch.
const DEFAULT_PURGE_BATCH_SIZE = 500;
const MAX_PURGE_BATCH_SIZE = 5000;

// Every table with a foreign key to raw_posts (migrations 002 and 004), in
// delete order: the score rows reference decision_audit_log via audit_id, so
// they go first; decision_audit_log goes last before raw_posts itself.
// tests/integration/compact.test.js reads the live catalog (pg_constraint)
// and fails if a migration adds a raw_posts FK that is missing here.
// Table names are this fixed constant only, never input.
const DEMO_POST_DEPENDENTS = Object.freeze([
    'sentiment_results',
    'relevance_results',
    'discourse_results',
    'post_embeddings',
    'decision_audit_log',
]);

// Stated on every purge's retention-log row.
const DEMO_PURGE_LEGAL_BASIS =
    'Not personal data: fictional demo content generated by scripts/populate.js ' +
    "(data_sources.source_type = 'demo'), never collected from a real source. " +
    'Deleted with its score, audit and correlation rows at the retention boundary ' +
    '(owner decision 2026-09-29).';

// Optional CLI argument: compact a specific month (YYYY-MM), else auto-detect
// Optional CLI argument (read in main, so requiring this module has no effect).
let targetMonth = null;

function getCutoffDate() {
    const d = new Date();
    d.setDate(d.getDate() - retentionDays());
    return d;
}

function firstOfMonth(date) {
    return new Date(date.getFullYear(), date.getMonth(), 1).toISOString().split('T')[0];
}

async function getMonthsToCompact() {
    if (targetMonth) {
        // Validate format
        if (!/^\d{4}-\d{2}$/.test(targetMonth)) {
            throw new Error(`Invalid month format: ${targetMonth}. Expected YYYY-MM.`);
        }
        return [targetMonth + '-01'];
    }

    // P10-2: only months that END before the cutoff (every post of the month
    // is past the detail window), with real (non-demo) posts, not yet
    // compacted. The month holding the cutoff waits until it is whole.
    //
    // PR #22 principal #7: no DISTINCT DATE_TRUNC over every raw_posts row
    // (a growing sequential scan). Walk month to month instead: each step is
    // one range query on the collected_at index — the earliest real post at
    // or after the previous month's end — so the cost is one indexed lookup
    // per month that has posts, compacted months skipped.
    const cutoff = getCutoffDate();
    const done = new Set((await dbAll(
        `SELECT TO_CHAR(compacted_month, 'YYYY-MM-DD') AS m FROM compaction_log`)).map(r => r.m));
    const months = [];
    let from = null;
    for (;;) {
        const row = (await dbAll(`
            SELECT TO_CHAR(DATE_TRUNC('month', rp.collected_at), 'YYYY-MM-DD') AS m,
                   TO_CHAR(DATE_TRUNC('month', rp.collected_at) + INTERVAL '1 month', 'YYYY-MM-DD') AS next
            FROM raw_posts rp
            JOIN data_sources ds ON ds.id = rp.source_id
            WHERE ds.source_type <> $2
              AND rp.collected_at < DATE_TRUNC('month', $1::timestamptz)
              AND ($3::date IS NULL OR rp.collected_at >= $3::date)
            ORDER BY rp.collected_at ASC
            LIMIT 1
        `, [cutoff.toISOString(), DEMO_SOURCE_TYPE, from]))[0];
        if (!row) break;
        if (!done.has(row.m)) months.push(row.m);
        from = row.next;
    }
    return months;
}

/**
 * Compact one month (spec §19), inside the caller's transaction:
 *   1. topic and source rollups over the month's real posts (scores stay
 *      valid after a post's text is removed, so blanked posts are counted);
 *   2. the text of any real post of the month still stored is removed with
 *      the retention mechanism (src/collectors/retention.js: notice +
 *      text_removed_at, one true data_retention_log row per source batch) —
 *      raw_posts.content is NOT NULL, so it is never "nulled";
 *   3. the month's embeddings are deleted (re-computable, derived from text);
 *   4. ONE data_retention_log row 'compacted' and one compaction_log row,
 *      both with the true counts of what this call changed.
 * Demo posts are never rolled up, blanked or counted (they are purged whole).
 */
async function compactMonth(client, rollupMonth, { log = console.log } = {}) {
    log(`  Compacting ${rollupMonth}...`);
    const monthStart = rollupMonth;
    const monthEnd   = new Date(new Date(rollupMonth).setMonth(new Date(rollupMonth).getMonth() + 1))
                           .toISOString().split('T')[0];

    // Step 1: topic rollups (keyword-based in Phase 1; BERTopic in Phase D).
    const topic = await client.query(`
        INSERT INTO monthly_topic_rollups
            (rollup_month, topic_label, source_category, location, language,
             post_count, positive_count, neutral_count, negative_count, avg_comparative)
        SELECT
            $1::DATE                         AS rollup_month,
            COALESCE(kw.keyword, 'general')  AS topic_label,
            ds.category                      AS source_category,
            NULLIF(rp.location, '')          AS location,
            rp.language                      AS language,
            COUNT(*)                         AS post_count,
            COUNT(*) FILTER (WHERE sr.indicator = 'positive') AS positive_count,
            COUNT(*) FILTER (WHERE sr.indicator = 'neutral')  AS neutral_count,
            COUNT(*) FILTER (WHERE sr.indicator = 'negative') AS negative_count,
            AVG(sr.comparative)              AS avg_comparative
        FROM raw_posts rp
        JOIN data_sources ds         ON ds.id = rp.source_id
        JOIN sentiment_results sr    ON sr.raw_post_id = rp.id
        LEFT JOIN LATERAL (
            SELECT rr.matched_keywords[1] AS keyword
            FROM relevance_results rr WHERE rr.raw_post_id = rp.id LIMIT 1
        ) kw ON TRUE
        WHERE rp.collected_at >= $2 AND rp.collected_at < $3
          AND ds.source_type <> $4          -- P9-3: demo feeds never rolled up
        GROUP BY rollup_month, topic_label, source_category, location, language
        ON CONFLICT DO NOTHING
    `, [monthStart, monthStart, monthEnd, DEMO_SOURCE_TYPE]);

    // Step 1b: source rollups
    const source = await client.query(`
        INSERT INTO monthly_source_rollups
            (rollup_month, source_id, source_category, post_count,
             positive_count, neutral_count, negative_count, avg_comparative)
        SELECT
            $1::DATE          AS rollup_month,
            rp.source_id,
            ds.category       AS source_category,
            COUNT(*)          AS post_count,
            COUNT(*) FILTER (WHERE sr.indicator = 'positive') AS positive_count,
            COUNT(*) FILTER (WHERE sr.indicator = 'neutral')  AS neutral_count,
            COUNT(*) FILTER (WHERE sr.indicator = 'negative') AS negative_count,
            AVG(sr.comparative)                               AS avg_comparative
        FROM raw_posts rp
        JOIN data_sources ds       ON ds.id = rp.source_id
        JOIN sentiment_results sr  ON sr.raw_post_id = rp.id
        WHERE rp.collected_at >= $2 AND rp.collected_at < $3
          AND ds.source_type <> $4          -- P9-3: demo feeds never rolled up
        GROUP BY rollup_month, rp.source_id, source_category
        ON CONFLICT (rollup_month, source_id) DO NOTHING
    `, [monthStart, monthStart, monthEnd, DEMO_SOURCE_TYPE]);

    // Real posts of the month (the count the log rows state).
    const { count } = (await client.query(`
        SELECT COUNT(*)::INTEGER AS count FROM raw_posts rp JOIN data_sources ds ON ds.id = rp.source_id
        WHERE rp.collected_at >= $1 AND rp.collected_at < $2 AND ds.source_type <> $3
    `, [monthStart, monthEnd, DEMO_SOURCE_TYPE])).rows[0];

    // Step 2: remove any text still stored (normally already removed by the
    // retention job at the end of the detail window).
    const live = (await client.query(`
        SELECT ds.name, array_agg(rp.id) AS ids
        FROM raw_posts rp JOIN data_sources ds ON ds.id = rp.source_id
        WHERE rp.collected_at >= $1 AND rp.collected_at < $2 AND ds.source_type <> $3
          AND rp.text_removed_at IS NULL
        GROUP BY ds.name
    `, [monthStart, monthEnd, DEMO_SOURCE_TYPE])).rows;
    let contentRemoved = 0;
    for (const row of live) {
        const src = getSource(row.name);
        const platform = !!(src && src.retention);
        const ids = await removeTextBatch(client, row.name, row.ids, {
            reason: platform ? `${src.retention.maxAgeHours}-hour retention window ended` : 'monthly compaction (spec §19)',
            rule: platform ? `${src.retention.maxAgeHours}-hour retention` : `${retentionDays()}-day detail window (spec §19)`,
            performedBy: 'scripts/compact.js', platform,
        });
        contentRemoved += ids.length;
    }

    // Step 3: delete the month's embeddings (real posts only).
    const embeddingResult = await client.query(`
        DELETE FROM post_embeddings
        WHERE raw_post_id IN (
            SELECT rp.id FROM raw_posts rp JOIN data_sources ds ON ds.id = rp.source_id
            WHERE rp.collected_at >= $1 AND rp.collected_at < $2 AND ds.source_type <> $3
        )
    `, [monthStart, monthEnd, DEMO_SOURCE_TYPE]);
    const embeddingsDeleted = embeddingResult.rowCount;

    // Step 4: one true retention row for the month, and the compaction log.
    await client.query(`
        INSERT INTO data_retention_log (raw_post_id, action, reason, legal_basis, performed_by)
        VALUES (NULL, 'compacted', $1, 'GDPR Article 5(1)(e) - Storage Limitation', 'scripts/compact.js')
    `, [JSON.stringify({
        summary: `Month ${monthStart} compacted into monthly rollups.`,
        month: monthStart, retention_days: retentionDays(), posts_in_month: count,
        topic_rollup_rows: topic.rowCount, source_rollup_rows: source.rowCount,
        texts_removed_now: contentRemoved, embeddings_deleted: embeddingsDeleted,
    })]);
    await client.query(`
        INSERT INTO compaction_log
            (compacted_month, posts_compacted, rollups_created, embeddings_deleted, content_nulled)
        VALUES ($1, $2, $3, $4, $5)
        ON CONFLICT (compacted_month) DO NOTHING
    `, [monthStart, count, topic.rowCount + source.rowCount, embeddingsDeleted, contentRemoved]);

    return { postsCompacted: count, embeddingsDeleted, contentNulled: contentRemoved, rollupsCreated: topic.rowCount + source.rowCount };
}

// ─── Demo purge (P9-3) ────────────────────────────────────────────────────────

/**
 * The demo scope, in SQL: of the given post ids, only those whose source is
 * a demo feed. Every purge DELETE filters through it, so a non-demo id that
 * reaches a delete (by a bug upstream or a crafted call) matches nothing.
 * $1 = DEMO_SOURCE_TYPE, $2 = uuid[] of candidate post ids.
 */
const DEMO_POSTS_IN = `
    SELECT rp.id
    FROM raw_posts rp
    JOIN data_sources ds ON ds.id = rp.source_id
    WHERE ds.source_type = $1
      AND rp.id = ANY($2::uuid[])`;

/**
 * Delete the given posts and every row referencing them — demo posts only.
 * The source_type filter is re-applied in each statement, so any id of a
 * non-demo post is ignored. Must run inside the caller's transaction.
 *
 * @param {import('pg').PoolClient} client
 * @param {string[]} postIds  candidate raw_posts ids
 * @returns {Promise<Record<string, number>>} rows deleted per table
 */
async function deleteDemoPosts(client, postIds) {
    const counts = {};
    for (const table of DEMO_POST_DEPENDENTS) {
        const r = await client.query(
            `DELETE FROM ${table} WHERE raw_post_id IN (${DEMO_POSTS_IN})`,
            [DEMO_SOURCE_TYPE, postIds],
        );
        counts[table] = r.rowCount;
    }
    const posts = await client.query(
        `DELETE FROM raw_posts WHERE id IN (${DEMO_POSTS_IN})`,
        [DEMO_SOURCE_TYPE, postIds],
    );
    counts.raw_posts = posts.rowCount;
    return counts;
}

/**
 * Purge ONE bounded batch of demo data older than the cutoff: up to
 * batchSize demo posts (with their dependent rows) and up to batchSize
 * demo-feed correlation sightings, then any pseudonymous profile those rows
 * pointed at that has no sighting and no post left. Writes one
 * data_retention_log row for the batch. Must run inside a transaction.
 *
 * @param {import('pg').PoolClient} client
 * @param {{ cutoff: Date, batchSize: number }} opts
 * @returns {Promise<null | { counts: Record<string, number>,
 *                            window: { from: string, to: string } }>}
 *          null when there was nothing left to purge.
 */
async function purgeDemoBatch(client, { cutoff, batchSize }) {
    const cutoffIso = cutoff.toISOString();

    // Oldest demo posts first; the rows are locked for the transaction.
    const posts = (await client.query(`
        SELECT rp.id, rp.collected_at, rp.pseudo_user_id
        FROM raw_posts rp
        JOIN data_sources ds ON ds.id = rp.source_id
        WHERE ds.source_type = $1
          AND rp.collected_at < $2
        ORDER BY rp.collected_at, rp.id
        LIMIT $3
        FOR UPDATE OF rp
    `, [DEMO_SOURCE_TYPE, cutoffIso, batchSize])).rows;

    const counts = posts.length > 0
        ? await deleteDemoPosts(client, posts.map(p => p.id))
        : Object.fromEntries([...DEMO_POST_DEPENDENTS, 'raw_posts'].map(t => [t, 0]));

    // Correlation sightings recorded against a demo feed (source-scoped, not
    // post-scoped), past the same boundary.
    const sightings = (await client.query(`
        DELETE FROM user_platform_sightings
        WHERE id IN (
            SELECT ups.id
            FROM user_platform_sightings ups
            JOIN data_sources ds ON ds.id = ups.source_id
            WHERE ds.source_type = $1
              AND ups.sighted_at < $2
            ORDER BY ups.sighted_at, ups.id
            LIMIT $3
        )
        RETURNING pseudo_user_id, sighted_at
    `, [DEMO_SOURCE_TYPE, cutoffIso, batchSize])).rows;
    counts.user_platform_sightings = sightings.length;

    // A profile is removed only when it was referenced by a purged demo row
    // AND no sighting or post (of any source) references it any more. Every
    // profile is created together with its first sighting, so one with real
    // evidence left always survives.
    const profileIds = [...new Set([
        ...posts.map(p => p.pseudo_user_id),
        ...sightings.map(x => x.pseudo_user_id),
    ].filter(Boolean))];
    counts.pseudonymous_users = profileIds.length === 0 ? 0 : (await client.query(`
        DELETE FROM pseudonymous_users pu
        WHERE pu.id = ANY($1::uuid[])
          AND NOT EXISTS (SELECT 1 FROM user_platform_sightings s WHERE s.pseudo_user_id = pu.id)
          AND NOT EXISTS (SELECT 1 FROM raw_posts rp WHERE rp.pseudo_user_id = pu.id)
    `, [profileIds])).rowCount;

    // Surviving profiles that lost sightings: recompute platform_count and
    // the sighting window from the sightings they still have, in this same
    // transaction, so no profile keeps a count that includes purged demo
    // evidence. platform_count is one per sighting row (1 at creation, +1
    // per repeat — migration 006's model; correlation itself is not
    // implemented, PR #22 grumpy M7), so the recount is COUNT(*) of the
    // remaining rows; a profile kept alive only by a post has 0. The
    // timestamps keep their old value when no sighting is left.
    counts.pseudonymous_users_recounted = profileIds.length === 0 ? 0 : (await client.query(`
        UPDATE pseudonymous_users pu
        SET platform_count   = agg.n,
            first_sighted_at = COALESCE(agg.first_at, pu.first_sighted_at),
            last_sighted_at  = COALESCE(agg.last_at,  pu.last_sighted_at)
        FROM (
            SELECT p.id,
                   COUNT(s.id)::INTEGER AS n,
                   MIN(s.sighted_at)    AS first_at,
                   MAX(s.sighted_at)    AS last_at
            FROM pseudonymous_users p
            LEFT JOIN user_platform_sightings s ON s.pseudo_user_id = p.id
            WHERE p.id = ANY($1::uuid[])
            GROUP BY p.id
        ) agg
        WHERE pu.id = agg.id
    `, [profileIds])).rowCount;

    if (counts.raw_posts === 0 && counts.user_platform_sightings === 0) return null;

    // Time window of the purged data (post collection and sighting times).
    const times = [...posts.map(p => p.collected_at), ...sightings.map(x => x.sighted_at)]
        .map(t => new Date(t).getTime());
    const window = {
        from: new Date(Math.min(...times)).toISOString(),
        to:   new Date(Math.max(...times)).toISOString(),
    };

    await client.query(`
        INSERT INTO data_retention_log (raw_post_id, action, reason, legal_basis, performed_by)
        VALUES (NULL, $3, $1, $2, 'scripts/compact.js')
    `, [JSON.stringify({
        summary: 'Fictional demo data past the retention boundary deleted.',
        retention_days: retentionDays(),
        cutoff: cutoffIso,
        window,
        counts,
        // The ids of the posts deleted (the lookup key for a job that finds
        // its post gone — src/pipeline/embeddings.js findDemoPurgeRecord).
        post_ids: posts.map(p => p.id),
    }), DEMO_PURGE_LEGAL_BASIS, DEMO_PURGE_ACTION]);

    return { counts, window, postIds: posts.map(p => p.id) };
}

/**
 * Purge all demo data older than the cutoff, one transaction per bounded
 * batch, until a batch finds nothing. Real (non-demo) data is never touched.
 * After the batches commit, `removeEmbedJobs(postIds)` (when given) removes
 * the purged posts' pending embed jobs; a failure there is reported, never
 * thrown — the purge is already committed and a leftover job no-ops.
 *
 * @param {{ cutoff?: Date, batchSize?: number, log?: Function,
 *           removeEmbedJobs?: (ids: string[]) => Promise<object> }} [opts]
 * @returns {Promise<{ batches: number, counts: Record<string, number>, embedJobs?: object }>}
 */
async function purgeDemoPosts({ cutoff = getCutoffDate(), batchSize, log = console.log, removeEmbedJobs } = {}) {
    const requested = batchSize ?? parseInt(process.env.DEMO_PURGE_BATCH_SIZE || '', 10);
    const size = Math.min(Math.max(Number.isInteger(requested) ? requested : DEFAULT_PURGE_BATCH_SIZE, 1),
        MAX_PURGE_BATCH_SIZE);

    const totals = {};
    const purgedIds = [];
    let batches = 0;
    for (;;) {
        const result = await dbTransaction(client => purgeDemoBatch(client, { cutoff, batchSize: size }));
        if (!result) break;
        batches += 1;
        purgedIds.push(...result.postIds);
        for (const [table, n] of Object.entries(result.counts)) totals[table] = (totals[table] || 0) + n;
        log(`  Demo purge batch ${batches}: ${result.counts.raw_posts} post(s), `
            + `${result.counts.user_platform_sightings} sighting(s) (${result.window.from} – ${result.window.to})`);
    }
    if (!removeEmbedJobs || purgedIds.length === 0) return { batches, counts: totals };
    let embedJobs;
    try {
        embedJobs = await removeEmbedJobs(purgedIds);
        if (embedJobs.removed || embedJobs.inFlight) {
            log(`  Demo purge: ${embedJobs.removed} pending embed job(s) of purged posts removed`
                + (embedJobs.inFlight ? `, ${embedJobs.inFlight} already running (they complete as no-ops)` : ''));
        }
    } catch (err) {
        embedJobs = { error: err.message };
        log(`  Demo purge: pending embed jobs not removed (${err.message}) — they complete as no-ops`);
    }
    return { batches, counts: totals, embedJobs };
}

/* istanbul ignore next -- binds the real BullMQ embed queue; tests inject */
function defaultRemoveEmbedJobs(ids) {
    const { embedQueue } = require('../src/queues/index');
    return require('../src/queues/embed-cleanup').removePendingEmbedJobs(embedQueue, ids);
}

/**
 * The whole job without the CLI: demo purge first, then every due month.
 * Used by the worker's maintenance job. @returns {Promise<object>} counts
 */
async function runCompaction({ log = console.log, removeEmbedJobs = defaultRemoveEmbedJobs } = {}) {
    retentionDays();   // M1: a bad window throws here, before the purge
    const purge = await purgeDemoPosts({ log, removeEmbedJobs });
    const months = await getMonthsToCompact();
    const total = { months: months.length, postsCompacted: 0, embeddingsDeleted: 0, contentNulled: 0 };
    for (const month of months) {
        const r = await dbTransaction(client => compactMonth(client, month, { log }));
        total.postsCompacted += r.postsCompacted;
        total.embeddingsDeleted += r.embeddingsDeleted;
        total.contentNulled += r.contentNulled;
    }
    return { demoPurge: purge, ...total };
}

/* istanbul ignore next -- CLI entry point */
async function closeQueuesIfLoaded() {
    const key = require.resolve('../src/queues/index');
    if (!require.cache[key]) return;
    const queues = require.cache[key].exports;
    await Promise.allSettled(Object.values(queues).filter(q => q && typeof q.close === 'function').map(q => q.close()));
}

/* istanbul ignore next -- CLI entry point */
async function main() {
    targetMonth = process.argv[2] || null;
    // PR #22 security L3: every CLI line goes through the secret scrubber.
    const { log } = require('../src/workers/logging');
    const console = { log };

    // P9-3: demo data past the retention boundary is deleted first, so it is
    // never compacted (and never reaches a rollup). The purged posts' pending
    // embed jobs are removed (the queue is opened only when a post was purged).
    const purge = await purgeDemoPosts({ removeEmbedJobs: defaultRemoveEmbedJobs, log });
    await closeQueuesIfLoaded();
    console.log(purge.batches === 0
        ? '✓ No demo data past the retention boundary.'
        : `✓ Demo purge: ${purge.counts.raw_posts} post(s) in ${purge.batches} batch(es).`);

    const months = await getMonthsToCompact();

    if (months.length === 0) {
        console.log('✓ Nothing to compact — all months within detail window or already compacted.');
        await closePool();
        return;
    }

    console.log(`Compacting ${months.length} month(s): ${months.join(', ')}`);

    let total = { postsCompacted: 0, embeddingsDeleted: 0, contentNulled: 0 };

    for (const month of months) {
        const result = await dbTransaction(client => compactMonth(client, month, { log }));
        total.postsCompacted   += result.postsCompacted;
        total.embeddingsDeleted += result.embeddingsDeleted;
        total.contentNulled     += result.contentNulled;
    }

    console.log(`✓ Compaction complete:`);
    console.log(`  Months processed:   ${months.length}`);
    console.log(`  Posts compacted:    ${total.postsCompacted}`);
    console.log(`  Embeddings deleted: ${total.embeddingsDeleted}`);
    console.log(`  Texts removed:      ${total.contentNulled}`);

    await closePool();
}

/* istanbul ignore next -- CLI entry point */
if (require.main === module) {
    main().catch(err => {
        // PR #22 security L3: scrubbed (a DB error can carry connection details).
        require('../src/workers/logging').logError(`✗ Compaction failed: ${err && err.message}`);
        process.exit(1);
    });
}

module.exports = {
    getMonthsToCompact, compactMonth, runCompaction,
    purgeDemoPosts, purgeDemoBatch, deleteDemoPosts,
    DEMO_POST_DEPENDENTS, DEMO_PURGE_LEGAL_BASIS,
};
